### ISSUE TITLE
SSplotNumber when called from SS_plots

### ISSUE THREAD

**Issue by yukio-takeuchi** [r4ss/r4ss#113]
When SS_plots is applied to multi region model, it crashes as

QuartzBitmap_Output - unable to open file './/plots/.//plots/numbers1_area 1_sex1_beg.png'

**Comment by taylori** [comment]
Thank you @yukio-takeuchi for reporting this.

There are two potential causes of this issue. One was in the creation of the file paths, which was fixed in a change to the function 4 days ago:
https://github.com/r4ss/r4ss/commit/7b0d60d312d0c9d6ad4e93c213280b0ddd3afa62
The other is the space in the filename, which fixed just now:
https://github.com/r4ss/r4ss/commit/9e3b7e32c9f85ac1354df1a333f519ec81b49fe0

Please try updating r4ss from GitHub and report whether the issue has gone away or not.

**Comment by taylori** [comment]
I think this issue has been adequately sorted out so now closing.
