### ISSUE TITLE
plotInfoTable no longer writes full file paths

### ISSUE THREAD

**Issue by melmonk** [r4ss/r4ss#122]
The "file" column of the plotInfoTable no longer writes the full file path for the figures.  I can either modify the assessment template code, or the file paths can be added back into the plotInfoTable.

**Comment by taylori** [comment]
Thanks @melmonk. The change was related to issue #110. The absolute paths were creating problems if the user wanted to define a folder for plotting relative to the working directory. Unfortunately it looks like the change was actually incomplete because in a few cases (such as catch plots), there are still full paths written. 

It would be easy to provide full paths in plotInfoTable while still allowing the plotdir argument to be a relative path. However, it seems possible that a user would want to move or rename the location of the plots and model output before compiling an assessment document? In such cases, creating the full path within the template might be preferred if it's not too hard.

In the short term, I'm happy to do whatever is best to get things working for you.

**Comment by melmonk** [comment]
Sorry for the slow response @taylori .  This morning, the GitHub version of r4ss isn't writing the ts_summaryF.png, which is stopping SS_plots and not finishing the plot output or writing plotInfoTable.  I wasn't getting this error yesterday and I think I can come up with an easy workaround for the template once I have the newer version of plotInfoTable working again. Thanks!

Error in png(filename = file.path(plotdir, file), width = pwidth, height = pheight,  : 
  unable to start png() device
In addition: Warning messages:
1: In png(filename = file.path(plotdir, file), width = pwidth, height = pheight,  :
  unable to open file 'C:/StockAssessment_template/r4ss/plots_mod1/C:/StockAssessment_template/r4ss/plots_mod1/ts_summaryF.png' for writing
2: In png(filename = file.path(plotdir, file), width = pwidth, height = pheight,  :
  opening device failed

**Comment by melmonk** [comment]
@taylori I create the file paths within the R code for the stock assessment template, so no need to edit the plotInfoTable.
