### ISSUE TITLE
Problems with SS_readctl_3.24

### ISSUE THREAD

**Issue by iagomosqueira** [r4ss/r4ss#124]
I am trying to load a ctl file, which can be found here

https://github.com/iotcwpm/ALB/tree/master/ioalbmse/inst/sa/2016

using
```r
ctl <- r4ss::SS_readctl_3.24("abt.ctl", verbose=TRUE,
  nseas = 4, N_areas=1, Nages=14, Ngenders=2, Nfleet=11,
  Nsurveys=5)
```

and I am finding some problems, maybe not all due to r4ss.

(1) I have nat_M option 4, but two genders, so two vectors specified. Then in line 322 of SS_readctl_33.24.R this call

```r
ctllist<-add_df(ctllist,name="M_parms",nrow=N_M_parms,ncol=14,
                  col.names=c("LO", "HI", "INIT", "PRIOR",
                             "PR_type", "SD", "PHASE",
                             "env_var","use_dev", "dev_minyr",
                             "dev_maxyr", "dev_stddev", "Block", "Block_Fxn"))
```

fails as I have no M_parms, so nrow=0

(2) In line 489

```r
    if(Do_Q_detail)
```

fails as Do_Q_detail has not been set anywhere

(3) In line 533

```r
  size_selex_Nparms[j]<-selex_patterns[size_selex_pattern_vec[j]+1]
```

a warning is issued for "number of items to replace is not a multiple of replacement length"

(4) I have in abt.ctl

```
#_size_selex_types
#_Pattern Discard Male Special
#1 0 0 0 #  1 F1_LL1
24 0 0 0 #  1 F1_LL1
15 0 0 1 #  2 F2_LL2
24 0 0 0 #  3 F3_LL3
15 0 0 3 #  4 F4_LL4
24 0 0 0 #  5 F5_DN3
15 0 0 5 #  6 F6_DN4
24 0 0 0 #  7 F7_PS1
15 0 0 5 #  8 F8_Other1
15 0 0 5 #  9 F9_Other2
15 0 0 5 # 10 F10_Other3
15 0 0 5 # 11 F11_Other4
15 0 0 1 # 12 CPUE_LL1
15 0 0 1 # 13 CPUE_LL2
15 0 0 3 # 14 CPUE_LL3
15 0 0 3 # 15 CPUE_LL4
15 0 0 5 # 16 CPUE_DN4
```

but I get

```
$size_selex_types
                     Pattern Discard Male Special
#_size_selex_types1      -20       3  -10     -10
#_size_selex_types2       -1      99    2      -6
#_size_selex_types3        6       0    0       0
#_size_selex_types4        1      -4   -6       6
#_size_selex_types5        0       0    0       1
#_size_selex_types6       -4      -6    6       0
#_size_selex_types7        0       0    1      -4
#_size_selex_types8       -6       6    0       0
#_size_selex_types9        0       1   -4      -6
#_size_selex_types10       6       0    0       0
#_size_selex_types11       1      -4   -6       6
#_size_selex_types12       0       0    0       1
#_size_selex_types13      -4      -6    6       0
#_size_selex_types14       0       0    1      -4
#_size_selex_types15      -6       6    0       0
#_size_selex_types16       0       1   -4      -6
```

and this then causes other problems.

Are there limitations on what SS_readctl can do in terms of dimensionality? Anything obviously particular in this ctl file that makes it fail?

**Comment by iagomosqueira** [comment]
For (1) I am adding

```r
if(N_M_parms > 0) {
  ctllist<-add_df(ctllist,name="M_parms",nrow=N_M_parms,ncol=14,
    col.names=c("LO", "HI", "INIT", "PRIOR",
    "PR_type", "SD", "PHASE",
    "env_var","use_dev", "dev_minyr",
    "dev_maxyr", "dev_stddev", "Block", "Block_Fxn"))
  }
```

in line 320, not sure this is right at this point.

**Comment by taylori** [comment]
Hi Iago,
Thanks for reporting this issue. I previously thought that parsing the control files was too difficult and this function would never get written, but @yukio-takeuchi stepped up and put this together. However, since the control file can have countless combinations of features, there are definitely limitations on what the function works for and you've revealed some of them. It's Thanksgiving holiday time for me so I'm unlikely to get to this until next week. I'm not sure if Yukio will have time to look at this but he might be able to fix it faster. You're also welcome to attempt some fixes and send pull requests if you're really enthusiastic.

**Comment by yukio-takeuchi** [comment]
Hi Iago and Ian

As Ian mentioned, it is techinically tough to enable to read  all the combinations of features of control file, while I made my best. One of the problem was that ctl files I have does not always covers all features. Anyway I will fix the problem probably during weekend or at late next week. Sorry for your patience

**Comment by iagomosqueira** [comment]
Nothing to apologise, I am really amazed you have managed to get so much in those functions. I am also using SS_readdat with great success.

See if my suggestion above makes sense in a file with option 3 or 4 for nat_M.

I might try digging a bit more into it and will let you know.

**Comment by iagomosqueira** [comment]
For the record, @yukio-takeuchi has done a great job and adapted both SS_readctl and SS_writectl to the particular settings in this ctl file. I can now use them to load, modify and then resave the ctl file. I assume those changes will be pushed up to master at some point. Meantime, the new versions can be found at https://github.com/iotcwpm/ALB/tree/master/ioalbmse/R

**Comment by taylori** [comment]
Updated read/write control files now on main r4ss GitHub page thanks to commit https://github.com/r4ss/r4ss/commit/4b757ff382fdd15747a3c14eb2b26382dc42507f from @yukio-takeuchi. Surely these functions don't yet work for all model configurations but we can probably close the issue now unless @iagomosqueira has additional concerns.

**Comment by iagomosqueira** [comment]
Works for my model configuration so far. On the precision issue when writing numbers to ctl, wl() and wl.vector() might also need to be considered, unless they are only used to write integers. Probably a call to format() inside writeLines would work. Can give it a go if it is needed.

**Comment by yukio-takeuchi** [comment]
The issue to keep original precision used in the original ctl and dat files may be further complicated.
First of all, in SS_readctl_3.24 and SS_readdat_3.24, I "copied" a function, probably written by Ian, which read a input file ignoring comments and splitting with space characters and converts to a numeric vector.
In order to obtain a numeric vector, it uses "as.numeric" function.  Numerical precision of "as numeric" depends on R's system option "digits" which you can check by typing
options()$digits 
on your R's console.

In my Windows PC and Linux VM , it was 
> options()$digits
[1] 7
We might need to set larger value to digits like
options(digits=9)

**Comment by iagomosqueira** [comment]
gdata::write.fwf uses format() for the final output, which uses options()$digits unless something else is specified. Same as print.default, which is called if you do print(numeric). SS_writectl could have a default option of using options()$digits, or a higher value, which the user can then change. Maintaining precision levels would be left in the hands of the user. Could this work?

**Comment by iagomosqueira** [comment]
One other small thing I will play with is keeping the rownames in some of the data.frames. For example, the SR params I have as

```
5 15 10.0589 11.4 -1 99 1 # SR_LN(R0)
0.2 1 0.8 0.75 -1 99 -4 # SR_BH_steep
0 2 0.6 0.4 -1 99 -1 # SR_sigmaR
-5 5 0 0 -1 99 -1 # SR_envlink
-10 10 0 0 -1 99 -1 # SR_R1_offset
0 0 0 0 -1 99 -1 # SR_autocorr
```

change to

```
  5.0	15	10.0589	11.40	-1	99	 1	#_SRparm1
  0.2	 1	 0.8000	 0.75	-1	99	-4	#_SRparm2
  0.0	 2	 0.6000	 0.40	-1	99	-1	#_SRparm3
 -5.0	 5	 0.0000	 0.00	-1	99	-1	#_SRparm4
-10.0	10	 0.0000	 0.00	-1	99	-1	#_SRparm5
  0.0	 0	 0.0000	 0.00	-1	99	-1	#_SRparm6
```

No big deal, but makes the new file a bit harder to read. I assume the code will need to keep those comments, if possible.

**Comment by yukio-takeuchi** [comment]
I agree that those features would be usefule. If we want to keep original digits of ctl and dat files perfectly. The best way is to read inputs as it is by reading and keeping characters instead of numerics and writing as characters. However, in practice, it may be easy to use larger digits before to call those functions and to set original values after that, since change of digits will have effects system wide.

As for the requests to keep original comments, I agree with your opinion. In the future version I am planning to update SS_read/write/ctl/dat to keep original comments if requested by a argument of those functions so that
SS_readctl3.24("alb.dat", keep.comments=T) to keep original comments
and if ctllist$keep.comments==T, SS_writectl(ctllist,"copy.ctl") will keep original comments. 
However this feature can not be added in a few days. Please be patient.

**Comment by iagomosqueira** [comment]
WRT the digits, I think it is useful having numbers, at least I need them as such to modify them according to certain rules. So maybe keeping the issue under the control of the user, by giving them the option to choose a valuedfor `digits`, would be enough.

As for the comments, no need to hurry, just something I noticed that would help navigating the new files.

**Comment by yukio-takeuchi** [comment]
There can be two scenarios for improvements of comments. The first one is to use similar comments made in ctl.ss_new created by SS. The second one is to keep original comments from the ctl file read. Probably the former may be easier to implement.

**Comment by kellijohnson** [comment]
Other software, notably [ss3sim](www.github.com/ss3sim/ss3sim) uses comments in the `ctl.ss_new`. Consequently, I would suggest we keep comments generated and written to a file by `r4ss` as like the `_new` files as possible.

**Comment by iagomosqueira** [comment]
That would be very useful

**Comment by taylori** [comment]
Note that another method to get comments is to run the model without
estimation and use control.ss_new itself. Of course that depends on the
control file being accurate and also might feel like a cumbersome step
within the context of a simulation analysis.
-Ian

**Comment by iagomosqueira** [comment]
After all the updates to read and write ctl and dat by @yukio-takeuchi, this is resolved at least for the models I am working with.
