### ISSUE TITLE
add automatic package testing via testthat

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#127]
Automatic of building the r4ss package is done via Travis-CI (https://travis-ci.org/r4ss/r4ss) but this could be improved by including example model output to test the core SS_output and SS_plots functions (to at least confirm that they don't crash). 

Information on testing is available at http://r-pkgs.had.co.nz/tests.html. Perhaps @kellijohnson has some ideas on setting this up based on her experience with https://github.com/ss3sim/ss3sim/tree/master/tests.

**Comment by taylori** [comment]
Testing implemented in adding_testthat branch with commits dbc66c11a8206513f145d863b820ea0f8ef92b7b, 31821da3c7153d5348bf21f171bc56ff8825586c, and 6f661f056f31cac4621c2c8e17c9039e340b620c. Will conduct further testing of tests and then merge.

**Comment by kellijohnson** [comment]
@taylori let me know if you need any help, 'testthat' is a pain to get in the habit of, but has saved me multiple times.

**Comment by taylori** [comment]
Branch has been merged as pull request #139, but leaving issue open for dialogue about refining tests.

Thanks @kellijohnson for offer of help. If you have time, feel free to look at
https://github.com/r4ss/r4ss/blob/master/tests/testthat.R
and
https://github.com/r4ss/r4ss/blob/master/tests/testthat/test_simple.R
Defining the path in testhat.R was something that @James-Thorson did in his corresponding files for VAST, but the path didn't seem to get passed to test_simple.R so I had to repeat that in the test file. I'm not really clear on what should go in each function and/or if tests should be divided among multiple files in /tests/testhat/ or all piled in one.

**Comment by kellijohnson** [comment]
The path, or any object, defined in [`testthat.R`](https://github.com/r4ss/r4ss/blob/master/tests/testthat.R#L5) will not be passed to the test stored in the folder `tests/testthat`. Instead, only the environment from the package listed in `test_check()` will be passed. Objects within a testing file (e.g., 'test_simple.R') will be saved while running all tests in that file, but again the objects will not be shared across multiple files. Basically, the `testthat.R` file is just so devtools and R CMD check can do their thing. 

File structure within 'test/testthat' can be specific to the needs of package developers. With `ss3sim` we tried to group tests based on major parts of the package. That way if you were working on package development you could essentially run `testthat::test_file("test_filename.R")` without needing to run all tests because eventually running all tests can become quite lengthy. It also makes sense to groups tests that share objects because, like I mention above, objects are not shared across files. For instance, if you were to manipulate a control file and want to check for multiple things using that single file you would want all test contained within a single file. Also, we have checks that are run on local computers, but skipped on CRAN (e.g., `skip_on_cran()`) that are stored in single files because it requires running a model.

**Comment by taylori** [comment]
The testthat setup was working well to automatically check commits to r4ss until recently when failure messages began appearing which seem unrelated to the changes I made:
```
E: Unable to locate package r-cran-devtools
E: Package 'r-cran-testthat' has no installation candidate
```
(see https://travis-ci.org/r4ss/r4ss for more detail).

If someone is aware of something that can be done to get it working again, please speak up.

Also, while looking through the errors, I see messages about "r-travis is DEPRECATED!". 
The r4ss package uses r-travis because of a dependency on the tcltk package (which is now just in "Suggests", not "Imports"--see issue #48). Perhaps @kellijohnson or @seananderson have some ideas on whether use of r-travis is related to the other issue. It's perhaps time to simply remove the tcltk-related functions, regardless.

**Comment by seananderson** [comment]
Does the current ss3sim config work?
https://github.com/ss3sim/ss3sim/blob/master/.travis.yml

I think the 'before script' part might have been for tcltk, but I can't remember right now.

**Comment by taylori** [comment]
Copying the current ss3sim config made the message about r-travis being deprecated go away but missing devtools problem is still present. Looks like the error has only occurred in the most recent builds of r4ss, https://travis-ci.org/r4ss/r4ss/builds, so perhaps ss3sim will face a similar problem when the next commit is made (unless the underlying issue is fixed first).

**Comment by seananderson** [comment]
Solution here: https://github.com/travis-ci/travis-ci/issues/7654

Add dist:trusty (or wait a few weeks for this to be the default distribution).

**Comment by taylori** [comment]
That did the trick. Thank you @seananderson !
Since both Travis and testthat seem to be working well and @kellijohnson provided good input on how to structure the testthat files, Ill close this issue now.
