### ISSUE TITLE
update read/write forecast functions to work on 3.30

### ISSUE THREAD

**Issue by taylori** [r4ss/r4ss#128]
Could use either wrapper as with read/write functions for data or just have switches within the file since the changes aren't too significant.

**Comment by yukio-takeuchi** [comment]
My comment is slightly remote from Ian's initial issue. SS3.24 accepts option not to conduct projection by setting Do_Forecast=0 in forecast.ss. If Do_Forecast=0, ss does not read rests of them. When SS3.24 finished its execution it write a forecast.ss_new with missing components for forecast specifications after D_Forecast. SS3.30, when I tested, seems to work slightly differently. It accepts Do_Forecast=0, but write forecast.ss_new with Do_Forecast=4 with complete (at the minimum level) forecast specifications. 
WRT SS_readforecast, when it read forecast.ss for SS3.24 with Do_Forecast=0 with incomplete forecast specification it crashed, since SS_forecast assumes that forecast.ss is complete even if Do_forecast=0.
Then there may be two issues 1) will current behavior of SS3.30 as for reading forecast.ss continue when it is released?, 2) is it better to change behaviour of SS_read/writeforecast to be consistent with SS3.24/3.30 respectively.
Nevertheless if "complete" forecast.ss is used, it seems that wrapper function is not necessary if version (3.24 or 3.30) is properly identify manually or automatically.

**Comment by taylori** [comment]
Recent update to SS_readforecast makes progress to sorting these things out. User input for "version" determines expectation for 3.24 or 3.30 format. The function now matches behavior of SS in ignoring anything after Forecast=0 unless new input "readAll" is set to TRUE.

Remaining tasks:
1. Finish section on processing lower part of forecast file for 3.30 models
2. Revise SS_writeforecast to work with 3.30 models and to stop writing if Forecast=0 and writeAll=FALSE.

**Comment by taylori** [comment]
Updated code in commits c74036f and 3482ef5 now works with 3.30 after testing on a few different models. Optional inputs such as max catch by fleet or area or allocation group are not yet supported in SS_readforecast, but can be easily added in the future and are rarely used and not necessarily a high priority, so closing this issue.
