### ISSUE TITLE
End year and depletion

### ISSUE THREAD

**Issue by kellijohnson** [r4ss/r4ss#130]
@taylori Quick question, and probably does not warrant an issue, but here it is.
In `SSoutput` the `ts` is derived from `timeseries[timeseries$Yr <= endyr + 1, ]`, and consequently depletion for the current year is then calculated from the last row of this data frame and the first row. How come `r4ss` uses `endyr + 1`, when this is also the first year of forecasts for the current depletion?
Thank you in advance for any information regarding the reasoning behind this. Also, why is Bratio not used, where SS provides an estimate of variance for this rather than having `r4ss` calculate depletion?

**Comment by taylori** [comment]
Good question @kellijohnson. In a typical application of SS, endyr is defined as the final year of data, but in our assessment reports we often want to report the start-of-year biomass for endyr+1, the first forecast year, which doesn't actually depend on any of the forecast settings, only having the forecast turned on (which will happen be default in SS version 3.30). 

For instance, U.S. West Coast Groundfish assessments conducted this Spring will have total catch, age and/or length compositions, and indices of abundance that are complete through 2016, but our assessment documents will report spawning biomass and other quantities of interest for the start of 2017.

For most models, Bratio indeed reports relative spawning biomass (a.k.a. depletion) and should match the timeseries calculation of B_y / B_0 (with the additional benefit of providing uncertainty around that ratio) but it can be problematic because there is a starter file input that allows it to be spawning biomass relative to something other than B0: 
`1 # Depletion basis:  denom is: 0=skip; 1=rel X*B0; 2=rel X*Bmsy; 3=rel X*B_styr`

Ultimately, lots of these calculations as conducted by r4ss haven't changed in a long time even if they aren't the most logical or efficient approach, just one that seems to work. I'm happy to help make changes if there are problems with the current approach or interest in cleaning things up.

**Comment by kellijohnson** [comment]
@taylori thanks for the explanation, and the way you have it is just fine. I am closing this now.
