### ISSUE TITLE
Fixed read of age comps - broken?

### ISSUE THREAD

**Issue by CWetzel** [r4ss/r4ss#137]
I loaded the newest version from github and now I am receiving an error when using the SS_output function on a SS 3.30 model.  The tagging composition data is the last item to correctly finish prior to this error:
Error in if (nrow(fit_age_comps) > 0) { : argument is of length zero

**Comment by taylori** [comment]
Attempted fix just uploaded with commit b982a77.  The issue was yesterday's update to SS_output relied on a header that was added sometime between SS versions 3.30.01.09 and 3.30.01.12. Revised function should work with and without the header but those using the older SS versions won't get the $Age_comp_Eff_N_tuning_check output.

**Comment by CWetzel** [comment]
IT to the rescue!
