### ISSUE TITLE
Update par file name when SS_profile when running from par file  

### ISSUE THREAD

**Issue by CWetzel** [r4ss/r4ss#163]
The SS_profile function currently writes the par file name as ss3.par which is no longer correct for version 3.30.  Need to add a check for SS version to determine the correct par file name for SS to use.

**Comment by taylori** [comment]
Thanks @CWetzel for reporting this. The function was using the "parfile" input in some places but not others. That should be fixed in commit b97754c.

Note that there are two ways to run using the parfile:

- `usepar=TRUE, globalpar=FALSE`: runs each step in the profile using the estimated parameters from the previous step. If the first model converges, this should improve speed and convergence for the subsequent models, but often our `profilevec` inputs begin at an extreme value which may not work well and cause subsequent steps in the profile to also have problems. In such cases, you could run separate profiles in either direction from the estimated value and then stitch the results together by combining the list of model output lists before running `SSsummarize`.

- `usepar=TRUE, globalpar=TRUE`: uses the original par file for all model runs. This reduces the chance of one bad model messing up the rest but probably won't improve speed as much.

Lastly, note that if you're using a parfile, you may want to start in a later phase when recdevs are estimated since the parfile will include non-zero recdevs values (if present in the model). This can be achieved using an input like `extras="-phase 10 -nox"`.

**Comment by taylori** [comment]
The fix seemed to work, so closing issue.
