### ISSUE TITLE
Need grep(..., fixed = T) in SStableComparisons() for "SR_LN(R0)"

### ISSUE THREAD

**Issue by John-R-Wallace** [r4ss/r4ss#164]
Note:
> grep("SR_LN(R0)", c("A", "SR_LN(R0)", "B"))
integer(0)

> grep("SR_LN(R0)", c("A", "SR_LN(R0)", "B"), fixed =T)
[1] 2

and FYI:
> grep("(R0)", c("A", "(R0", "B")) 
[1] 2

> grep("(R0", c("A", "(R0)", "B")) 
Error in grep("(R0", c("A", "(R0)", "B")) : 
  invalid regular expression '(R0', reason 'Missing ')''

So  SStableComparisons(),  and other places checking for items with "( )", need grep(..., fixed = TRUE):

vals <- bigtable[grep(name, bigtable$Label, fixed = TRUE), ]

I was inside SStableComparisons() to get out  "SR_LN(R0)" not "R0_billions"

To that end I used:

if (name %in% c("SR_R0", "R0")) {
                  vals[-1] <- round(exp(vals[-1])/1e+06, 6)
                  vals[1] <- "R0_billions"
}

if (name %in% c("SR_LN(R0)", "SR_LN.R0.")) {
                  vals[-1] <- round(vals[-1], 6)
                  vals[1] <- "LN_R0"

}

Which needs a proper explanation in the help.

**Comment by taylori** [comment]
Thanks @John-R-Wallace for the idea. grep with fixed=TRUE is used in many other places in r4ss but was clearly needed here.

I've added fixed=TRUE and some other changes in commit b97754c.
I didn't implement as you suggested, because "SR_R0" was just the name used in some earlier SS versions for the parameter now labeled "SR_LN(R0)". Instead, there's no processing of those parameters with R0 in the name but by default you now get both that parameter as well as "Recr_Virgin" (converted into billions or millions or thousands) which is what the R0 value was converted into in the old code.

I also changed the default years for relative spawning output and SPR to be those that a 2017 model would typically be interested in.

**Comment by John-R-Wallace** [comment]
Yes, I was also going to mention upgrading the default years for relative spawning output and SPR to be those that a 2017 model would typically be interested in.

What about the default being the end year of the first model + 1.  Since the first model is typical the base.  Then you don't have to change it each year.  

Using the actual calendar year as the default is what you end up doing manually, so that is an option also.

**Comment by taylori** [comment]
Automatic update of the year is a good idea, but it's likely that most users will want to revise the `names` input anyway, so I think the potential confusion of processing the names based on the current year isn't worth saving one minute per year in manual editing the default inputs.

**Comment by John-R-Wallace** [comment]
All the better if that minute is used up early in the year.  :-)
