### ISSUE TITLE
inconsistent formatting of output for McAllister-Ianelli tuning

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#168]
In the list produced by SS_output, $Length_comp_Eff_N_tuning_check and $Age_comp_Eff_N_tuning_check, which are used for the McAllister-Ianelli tuning method, are inconstant due to differences in Report.sso. In SS 3.30, the length output includes a "Recommend_Var_Adj" column which can be used to replace whatever you have in the variance adjustment section. This is calculated with SS as just Curr_Var_Adj * HarEffN / MeanInputN. In a commit to be issue in a moment, I've just added the equivalent "Recommend_Var_Adj" column to the Age comp section using the calculation: "Var_Adj" * "HarMean(effN)" / "inputN*Adj". Anyone applying this tuning method, please report if the values don't look reasonable.

**Comment by taylori** [comment]
Output has been cleaned up in commits 82a516d and 	c8b6191. Now both Age and Length comp tuning checks have consistent column names. 

Note that these sections are modified from Length_Comp_Fit_Summary and Age_Comp_Fit_Summary in the report file with some columns removed (for things not commonly used like the arithmetic mean of the effective sample size--as opposed to the harmonic mean).

Closing issue.

**Comment by taylori** [comment]
Reopening issue because the output `$Size_comp_Eff_N_tuning_check` reported for models that use the generalized size composition section, was not included in the recent clean up and alignment of `$Length_comp_Eff_N_tuning_check` and `$Age_comp_Eff_N_tuning_check`. These outputs may get cleaned up in a future version of SS in which case the processing in r4ss wouldn't be needed.

Also, to make their source more clear the tables reported by SS_output could be renamed to match the `*_Comp_Fit_Summary` names used in the report file.

**Comment by iantaylor-NOAA** [comment]
This tuning method is now less command and is primarily done via `r4ss::tune_comps()` so any remaining formatting issue (if any) no longer matter.
