### ISSUE TITLE
SS_output discard names

### ISSUE THREAD

**Issue by kellijohnson** [r4ss/r4ss#173]
Error in `SS_output` using version SS-V3.21 with discard names. When "Name" is not in the column names of `discard`, `discard$Fleet` is copied over, which is equal to `NA`. The `NA` values are then ran through `strsplit`, which causes an error. I think the following fix will work (to be inserted after line [1819](https://github.com/r4ss/r4ss/blob/master/R/SS_output.R#L1819)), but I did not want to push it to master without checking with @taylori or someone else more familiar with what is going on:
```if (is.na(discard$Name[i])) next```

**Comment by taylori** [comment]
In spite of the claim that "this function tested on SS-V3.21 through SS-V3.3", I haven't done any testing on models prior to 3.24 in a while, so it doesn't surprise me that there's an error. Go ahead an push a change since this line is in a section that only applies to versions up to 3.23 so there's little danger of impact to most users who are using 3.24 or 3.30. More satisfying might be to fill in the "Name" column properly, but I don't have a 3.21 model on hand to explore how to do that and getting the function to not crash is more important anyway.

**Comment by taylori** [comment]
This should be fixed in commit `ecf4399146289e5a0d9a43f6f2d611b299c1bc22` to the development branch. Closing issue.
