### ISSUE TITLE
Data-Limited Report File and SS_output

### ISSUE THREAD

**Issue by CWetzel** [r4ss/r4ss#187]
If the data-limited output option is selected in the starter file (option 2), the SS_output function errors out while reading the report file.

**Comment by taylori** [comment]
This issue wasn't dealt with earlier because of lack of example to replicate the problem. @John-R-Wallace just ran into it and provided an example which led to a simple change in commit c08130c that worked for at least this one case. I will close the issue but it can be opened again if anyone comes across another model setup where SS_output doesn't work when the run detail is set to 2.

The goal is to have the SS_output function work for all model configurations, but for those who aren't familiar, note that to get all output from SS (and all default r4ss plots), the starter file should have a value of 1 for this setting:
```
1 # run display detail (0,1,2)
```
where the 3.30 User Manual describes the options as follows:

```
Detailed age-structure report
  0 = omit catch-at-age for each fleet and cohort;
  1 = include all output;
  2 = reduce output for data-limited models
```
