### ISSUE TITLE
Fleet labeling for all data plots

### ISSUE THREAD

**Issue by CWetzel** [r4ss/r4ss#247]
The fleet labeling for some of the data, data fit, and index plots appears to no longer be the default. Was this changed intentionally?  

![index5_logcpuefit_east_trawl](https://user-images.githubusercontent.com/6172110/46233191-9de4ef00-c326-11e8-8979-9dfdd64cb424.png)

![comp_agefit_flt10mkt2_page1](https://user-images.githubusercontent.com/6172110/46233173-932a5a00-c326-11e8-9d76-f543ed73dd59.png)

**Comment by taylori** [comment]
The change to remove the plot titles was intentional but was done in a haphazard and incomlpete way. 

There's been a longstanding wish (described in issue #6) to be able to exclude the plot titles for inclusion in reports where that information will be included in the caption. The `mainTitle = TRUE/FALSE` input to `SS_plots` had been partially implemented in various of the functions that are called from `SS_plots` and in some recent commit I changed the default from TRUE to FALSE.

When browsing the plots in the HTML view, the captions should provide the fleet info, and the filename of the PNG files should have the fleet number as well.

Try running SS_plots(..., mainTitle=TRUE) to see if this brings the titles back. If not, I should fix that.

**Comment by CWetzel** [comment]
I just got around to checking this. Setting mainTitle = TRUE does solve this problem.  I am going to close this issue.
