### ISSUE TITLE
Explore Arni's plotMCMC package

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#25]
Google Code issue 95: See how much plotMCMC overlaps with r4ss functions mcmc.nuisance and mcmc.out.

**Comment by taylori** [comment]
I just looked at the plotMCMC package from @arnima-github at https://github.com/arnima-github/plotMCMC. There's lots of overlap and it would be nicer to not maintain `mcmc.out` and `mcmc.nuisance` functions in r4ss (which haven't gotten much support since they were written in 2003) when we could rely on the larger set of diagnostic plots in that package.

However, this is probably a low priority given that not many SS users are running MCMC, and making a change now would require some adaptation for the hake assessment being conducted over the next few months.

**Comment by taylori** [comment]
Cole Monnahan's adnuts package (at https://github.com/colemonnahan/adnuts) facilitates a new workflow for running MCMC with the new no-U-turn sampling algorithm that Cole added to ADMB 12.0. This approach includes parallel MCMC chains and doing multi-chain MCMC diagnostics using the ShinyStan package.

Demo use, associated with a forthcoming manuscript, is as demonstrated in the file https://github.com/colemonnahan/bayes_assess/blob/master/demo.R 

The status-quo MCMC tools in r4ss should probably just be kept in place as they are and re-evaluated sometime in the future after Cole's new tools have been explored by more SS users.

**Comment by taylori** [comment]
Should have flagged @colemonnahan on the previous comment.

**Comment by colemonnahan** [comment]
@taylori I don't use r4ss much anymore but I'd keep the functions that help make plots/tables for reports and such and leave the running and diagnostics to adnuts. But agreed, we can revisit this after more users try out the new software.

**Comment by arnima-github** [comment]
Hi guys! The plotMCMC package is fully maintained, just very stable since 2014 :)
Let me know if I can be of any help. Arni

**Comment by taylori** [comment]
Thanks @arnima-github. My initial thought (long ago) was to deprecate the existing MCMC plotting functions in r4ss and rely on plotMCMC. However, if future users of MCMC with SS focus on the new @colemonnahan approach, it's maybe not worth investing in a change from the status-quo (which would also require the small number of folks who use those functions to change their workflow). 

I'll reopen this issue to make it a more visible reminder to check back in about this during a less busy time.

**Comment by iantaylor-NOAA** [comment]
Closing this issue as part of a larger issue cleanup. Somewhat duplicated with #11 which can remain open for now. The relatively small number of MCMC users of SS3 are mostly using bespoke code for their plotting which is working OK.
