### ISSUE TITLE
SSplotProfile and PinerPlot function issue

### ISSUE THREAD

**Issue by zandjyo** [r4ss/r4ss#252]
There is an issue with the SSplotProfile function in that if you use an environmental variable on a natural mortality parameter the function will not run but rather give the error   "Multiple parameters matching profile.string" because the names for the parameters are too similar.

To solve this issue line 52 in the function should be changed from 
 parnumber <- grep(profile.string, pars$Label)
to
 parnumber <- match(profile.string, pars$Label)

A similar problem is encountered with the PinerPlot function again line 57 should be changed from
 parnumber <- grep(profile.string, pars$Label)
to 
 parnumber <- match(profile.string, pars$Label)

**Comment by taylori** [comment]
Good catch, Steve. I see now that `NatM_p_1_Fem_GP_1` is a subset of `NatM_p_1_Fem_GP_1_ENV_mult`, so there's no way to profile over the base M parameter without creating that error. This probably is an issue for many time-varying parameter configurations.

A convenience provided by `grep()` that you don't get with `match()` is the option to be lazy and specify a substring, such as `R0` for `SR_LN(R0)` or `steep` for `SR_BH_steep`, so instead of making the switch wholesale, there's a new `exact` argument in both functions which such that `exact=TRUE` would use `match()` and `exact=FALSE` would use `grep()`. The warning has now been augmented to suggest this: 
```
Error in SSplotProfile(SSsummarize(list(s1, s2)), profile.string = "NatM_p_1_Fem_GP_1") : 
  Multiple parameters matching profile.string='NatM_p_1_Fem_GP_1':
NatM_p_1_Fem_GP_1, NatM_p_1_Fem_GP_1_ENV_mult
You may need to use 'exact=TRUE'.
```

The change is in the development branch (commit 274337699b7e983316102d14df876c5e71ef1276), so to use this option, install using 
```
devtools::install_github("r4ss/r4ss", ref="development")
```

I'm hoping to test various recent changes in `development` and get them merged into the main trunk in the next day or two.

**Comment by taylori** [comment]
This issue seems to be adequately sorted out and the `development` branch has now been merged into `trunk`, so closing issue.
