### ISSUE TITLE
SSplotMnwt Updated based on SS version

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [r4ss/r4ss#288]
The naming of the columns in the replist$mnwgt section has changed from"Mkt" used to indicate the partition. I think SS 3.30 version changed the partition column to "Part".  I have pushed a fixed version in the development branch ab45fd5688143ac883ef0d00d256cb938ab512e9 for testing.

**Comment by taylori** [comment]
Thank you @CWetzel! Obviously I wasn't doing any testing with a model that had mean body weight data.

**Comment by CWetzel** [comment]
Even if you (@taylori) had you likely would not have noticed because there were no errors.  I finally realized that I was missing some figures.  The html page for the Mnwt shows each of the figures twice for some reason and has for a while I think.  Minor issue, but when someone has time this should be fixed.

**Comment by iantaylor-NOAA** [comment]
Fix seems to be working. Thanks @chantelwetzel-noaa, closing issue.
