### ISSUE TITLE
Re-evaluate how last year is calculated in SSplotComparison

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [r4ss/r4ss#313]
Currently, when not specified by the user, the "endyr" is determined based on the final model year as determined by the SSsummarize function.  The SSplotComparison function then uses this endyr to create all figures.  The F value figure, however, modifies this endyr to endy -1.  I don't this is correct.  This would be correct if we were creating the West Coast specific plots which want figures plotted through endy+1, where it would be correct to modify the endyr for F figures to endyr +1 -1.    

I wanted to run this by everyone to ensure that I have not misunderstood something.  I am more than happy to make this minor change if everyone agrees.

**Comment by iantaylor-NOAA** [comment]
The current behavior is definitely not right, but I'm not what the ideal would be. 

For a model such as one of our current west coast groundfish assessments where the data end in 2018 and the status at the start of 2019 is the focus of reference points and status determination, I think the current default will end the plots of spawning biomass in 2018 and F and SPR plots will end in 2017, which is definitely not right. For this case, shifting the default when endyrvec is not provided to last year of data +1 for everything but F and SPR which depend on catch make sense. However, if you input endyrvec = 2019, should the F and SPR plots include 2019 or override the input and change it to 2018? I suspect that if the user inputs a value, it should just get used. You can always re-run the function to make the F or SPR plots with a new endyrvec if you care to. Go ahead and make the change @chantelwetzel-noaa.

Sorry, I should have noticed this before since by default the function adds the final year to the figures and all my recent figures said 2018 instead of 2019. It's not too late to remake all the time series comparison figures in the Big Skate assessment to correct this.

**Comment by chantelwetzel-noaa** [comment]
This has been changed in ec6fd02b4a541500edf46404b4c3b43d106f8a7a to modify the end year plotted to endyr + 1 for stock status (biomass, recruitment) figures and endyr for F and SPR figures.
