### ISSUE TITLE
Development branch SSexecutivesummary

### ISSUE THREAD

**Issue by melmonk** [r4ss/r4ss#339]
In creating the numbers-at-age table, I receive the error "Error in strsplit(rawstarter[grep("detailed output", rawstarter)], " ") : 
  object 'rawstarter' not found"
If I create the rawstarter object outside SSexecutivesummary() and rerun the number-at-age table, it works.

**Comment by iantaylor-NOAA** [comment]
Should be fixed in commit 9e0ebca. I had the same issue last week but forgot to commit and push the fix to github. rawstarter was previously only read when making some earlier table in code that got skipped of you input `tables = 'numbers'`. But it was only needed if you had detailed output turned off so no numbers at age output. Now it gets read if needed in either place.
