### ISSUE TITLE
SS_readctl_3.24 throwing error in F_rates for F_method ==2

### ISSUE THREAD

**Issue by mkapur** [r4ss/r4ss#379]
I have a 2-area ctl file in 3.24 and trying to run SS_readctl_3.24 follows produces the following error:
```
  SS_readctl_3.24(file = paste0(tesme,"/Rep1/control_2Areas.ss"),#paste0(EMRep, "control_2Areas.ss"), 
                  # use_datlist = TRUE, 
                  # datlist = ,
                  version = 3.24,
                  N_areas = 2,
                  nseas =1,
                  Nages = 15,
                  Ngenders = 1,
                  Nfleet = 1, 
                  Nsurveys = 2,
                  echoall = TRUE)
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
In addition: Warning message:
In matrix(dat[i + 1:k - 1], nrow = nrow, ncol = ncol, byrow = TRUE) :
  data length exceeds size of matrix
```
Which `traceback()` suggests is in the F method setup (ca line 615). It appears it is expecting a dataframe of dim n X 6 with colnames `c("fleet", "yr", "seas", "Fvalue", "se", "phase"))`, whereas my CTL file in the relevant section looks like this (this is the .ss_new, hence the pasted F rates so you can see the structure -- but the error persists for the original CTL).

The model runs fine so I am unsure if there is something I am not specifying correctly in my function call.  I am happy to email whoever the full CTL if you'd like to take a look. I wonder if it is getting messed up because F_method[3] which becomes the nrows == 0?

```
#Fishing Mortality info 
0.1 # F ballpark for annual F (=Z-M) for specified year
-1999 # F ballpark year (neg value to disable)
2 # F_Method:  1=Pope; 2=instan. F; 3=hybrid (hybrid is recommended)
4 # max F or harvest rate, depends on F_Method
# no additional F input needed for Fmethod 1
# if Fmethod=2; read overall start F value; overall phase; N detailed inputs to read
# if Fmethod=3; read N iterations for tuning for Fmethod 3
 0.21 1 0 # overall start F value; overall phase; N detailed inputs to read
#Fleet Year Seas F_value se phase (for detailed setup of F_Method=2)

#
#_initial_F_parms
#_LO HI INIT PRIOR PR_type SD PHASE
 0 4.9 0 0 0 10000 -1 # InitF_1FisheryArea2

# F rates for Fmethod=2
# 0.143872 F_fleet_1_YR_1980_s_1
# 0.148219 F_fleet_1_YR_1981_s_1
# 0.152441 F_fleet_1_YR_1982_s_1
# 0.156386 F_fleet_1_YR_1983_s_1
[etc]
```
Full traceback() below.
```
7: stop("invalid 'row.names' length")
6: `.rowNamesDF<-`(x, value = value)
5: `row.names<-.data.frame`(`*tmp*`, value = value)
4: `row.names<-`(`*tmp*`, value = value)
3: `rownames<-`(`*tmp*`, value = paste0(paste0("#_", name, collapse = ""), 
       1:nrow))
2: add_df(ctllist, name = "F_setup2", nrow = ctllist$F_setup[3], 
       ncol = 6, col.names = c("fleet", "yr", "seas", "Fvalue", 
           "se", "phase"))
1: SS_readctl_3.24(file = paste0(tesme, "/Rep1/control_2Areas.ss"), 
       version = 3.24, N_areas = 2, nseas = 1, Nages = 15, Ngenders = 1, 
       Nfleet = 1, Nsurveys = dattemp$Nsurveys, N_tag_groups = ifelse(dattemp$do_tags == 
           0, NA, dattemp$do_tags), echoall = TRUE)
```

**Comment by k-doering-NOAA** [comment]
Hi @mkapur , thanks for reporting this - I think you correct that this is a bug. Note that
[this line in read_ctl_3.24](https://github.com/r4ss/r4ss/blob/development/R/SS_readctl_3.24.R#L615) expects the data frame, even though you specify 0 detailed inputs in your control file (in this line: ` 0.21 1 0 # overall start F value; overall phase; N detailed inputs to read`)

This was [corrected for 3.30 models](https://github.com/r4ss/r4ss/blob/development/R/SS_readctl_3.30.R#L809-L816) and I think the same fix can work. I can make this change first thing tomorrow morning, but if you would like to make the change yourself sooner, please feel free to submit a pull request.

A few more things to note about development of the read/write functions:
- A lot of the development recently has been focused on reading 3.30 model inputs, so the 3.24 functions are less likely to handle specialized setups and may have more bugs.
- It is better to use the wrapper functions (like `SS_readctl()` ) rather than the version specific ones(e.g., `SS_readctl_3.24`), as there is sometimes code that manipulates the files in the overall wrapper function (I know this is the case for SS_readctl). This is not ideal, but if you are having trouble  using a version specific function, it may be helpful to try the overall wrapper function.
- You can first read in a data file and then use it in the `SS_readctl` function to avoid having to specify many function inputs:
```
dat <- SS_readdat("mydat.ss", version = 3.24, verbose = FALSE)
ctl <- SS_readctl("myctl.ss", version = 3.24, use_datlist = TRUE, datlist = dat, verbose = FALSE)
```

**Comment by mkapur** [comment]
Thanks Kathryn, this can definitely wait till tomorrow as I currently have
a hack solution via readLines. Good point about the wrapper functions; I
only saw the nested call to this one so figured I’d dig in. And yes I was
aware of datlist but left it out of my post for clarity. Let me know when
you get a chance to push the ostensible fix and I’ll try it out.

**Comment by k-doering-NOAA** [comment]
@mkapur, could you test if the development branch works for you now?

**Comment by mkapur** [comment]
Sorry for the delay!! Dev branch worked, thank you so much. Feel free to
close.

**Comment by k-doering-NOAA** [comment]
Great! Thank you for reporting so the function could be improved for everyone.
