### ISSUE TITLE
returndat$SpawnOutputUnits default issue

### ISSUE THREAD

**Issue by latreesedenson** [r4ss/r4ss#418]
returndat$SpawnOutputUnits <-
  ifelse(!is.na(biology$Fecundity[1]) &&
           all(biology$Wt_len_F == biology$Fecundity),
         "biomass", "numbers"
  )

This defaults to "numbers" if there is nothing in the biology$Fecundity column, even if the true unit is "biomass." My work around currently is to take the units of the first fleet (model$catch_units) but I know that can go wrong with multiple fleets.

**Comment by iantaylor-NOAA** [comment]
Thanks for reporting this @latreesedenson. I'm not sure what circumstances would cause the biology$Fecundity column to be missing unavailable, but it makes sense to switch to biomass as the default in the absence of other information.

In theory, the units of catch as biomass or numbers as defined in the table near the top of the data file don't have to match the units of fecundity as defined in the control file under `#_fecundity option:(1)eggs=Wt*(a+b*Wt);(2)eggs=a*L^b;(3)eggs=a*Wt^b; (4)eggs=a+b*L; (5)eggs=a+b*W`.

There's a big section of code (https://github.com/r4ss/r4ss/blob/master/R/SS_output.R#L2330-L2387) immediately prior to those calculations related to determining the fecundity type and the associated parameters. However, as of SS version 3.30.12, the fecundity option is output at the top of Report.sso, so it probably makes sense to simplify all that code using the new output. That would facilitate calculating SpawnOutputUnits independently from biology$Fecundity based on the combination of the fecundity option and parameters.

**Comment by chantelwetzel-noaa** [comment]
@latreesedenson is your model a single-sex model?  I recently noticed an issue in the Report file section BIOLOGY for single-sex models.  The section has columns for female and male values but in the instance of a single sex model only one vector of sex specific values are written resulting in the column names not lining up.

**Comment by latreesedenson** [comment]
@iantaylor-NOAA thanks for clarifying that. I think @chantelwetzel-noaa got at another issue or maybe the real issue here, which is the possibility of the column names not matching up for a single sex model. 

Thanks for the quick reply.

**Comment by iantaylor-NOAA** [comment]
Thanks again for reporting this @latreesedenson. It looks like the extra column header has been present in that table for years without anyone detecting it. Changes from @k-doering-NOAA and myself in commits 4c8858a616b6d35681bf69da6061ece9b45fd4b3 and 9102758 should make the `SS_output()` function remove the extra `Wt_len_M` column header and correctly assign the values to the `Fecundity` column in 1-sex models so that the `$SpawnOutputUnits` will be output correctly for models with that header issue.

Also, thanks to @chantelwetzel-noaa and Rick Methot, the upcoming SS version 3.30.16 will also just have a single `Wt_len` column for 1-sex models rather the `Wt_len_F` and `Wt_len_M` which r4ss should now be robust to.

The r4ss changes are in the development branch available via
remotes::install_github("r4ss/r4ss", ref = "development")

**Comment by k-doering-NOAA** [comment]
@latreesedenson-NOAA was this issue solved?

**Comment by latreesedenson-NOAA** [comment]
@k-doering-NOAA I believe so.

**Comment by k-doering-NOAA** [comment]
Thanks! I'll go ahead and close this issue
