### ISSUE TITLE
Uncertainty missing from index plots in SSplotComparisons

### ISSUE THREAD

**Issue by Cole-Monnahan-NOAA** [r4ss/r4ss#434]
I can't get the uncertainty intervals to plot in this function. For instance if `x` is the result of `SSsumarize` and I run these three lines:

````
SSplotComparisons(x,  subplots=14, indexUncertainty=FALSE)
SSplotComparisons(x,  subplots=14, indexUncertainty=TRUE)
SSplotComparisons(x,  subplots=14, indexUncertainty=TRUE, indexPlotEach=TRUE)
````

The second plot does not have error bars and it seems like it should. I know the SE is there and working, because in the second one the y-axis limits are wider than the first (it uses the error bars to calculate them), and the third plot works and has error bars. The same thing happens for subplot=13.

Am I doing something wrong here? 

This is for r4ss 1.40.1 on R 3.6.3. I had a quick look at the code and can't see anything immediately wrong. 

![image](https://user-images.githubusercontent.com/58868176/97902823-f996b900-1cf2-11eb-875e-0b8e332910a7.png)

**Comment by Cole-Monnahan-NOAA** [comment]
Ok I dug into this a bit. The issue is here:

https://github.com/r4ss/r4ss/blob/RiskTableDevelopment/R/SSplotComparisons.R#L1295

The variable `subset` indexes the first model. So when you do `obs[subset]` it returns the obs values only for that model, and subsequently the `lower` and `upper` vectors also are only for this model. The problem arises later when you go to use it:

https://github.com/r4ss/r4ss/blob/RiskTableDevelopment/R/SSplotComparisons.R#L1369

`y0=lower[subset]` 

since `subset` is longer than `lower`, it returns NA values for `y0` and nothing is plotted. It's a very simple fix, just change

https://github.com/r4ss/r4ss/blob/RiskTableDevelopment/R/SSplotComparisons.R#L1295

from `y <- obs[subset]` to `y <- obs` like it is the previous clause for plotting all indices.

I checked this locally but don't have write privileges so I can't do a pull request. 

Two more things I'd do are: (1) Use the same subset logic here as above, checking for NAs in the likelihoods. I presume this is to ignore ghost data? In any case it's a potential bug. (2) Might be worth throwing a check for NA values in there somewhere.

**Comment by k-doering-NOAA** [comment]
Hi @Cole-Monnahan-NOAA , thanks for reporting and following up on this! @iantaylor-NOAA  is usually the one to troubleshoot issues  with SSplotComparisons, but he has been out of the office this week. I just sent you an invite so that you can have write privileges for r4ss; would you be able to submit a PR for this?

as for the two other suggestions, thanks for providing them! I'll let Ian comment more specifically when he has the chance.

**Comment by iantaylor-NOAA** [comment]
Hi Cole,
Sorry I was unavailable the last couple days and am still catching up on things. Thank you for reporting this bug and then digging deeper to find a solution.

I'm assuming we can remove the @colemonnahan account from the organization now that @Cole-Monnahan-NOAA is included (thanks @k-doering-NOAA).

Please go ahead with the bug fix as either Pull Request or push directly to the `development` branch (since it's so small and already discussed here).  If you have time and interest, you're also welcome to tackle any of the other things you propose, with a Pull Request as the better workflow for a larger set of changes.

I think that NA values can appear in any of the tables in SS output for a variety of reasons and I've generally tried to make the r4ss functions robust to their appearance, but have surely done that in a haphazard way.

**Comment by Cole-Monnahan-NOAA** [comment]
Hi @iantaylor-NOAA no worries about the delay.

Yes you can remove my old account @colemonnahan . Thanks for adding me as a developer. I'm a real SS user now so as I find r4ss bugs/improvements I'll happily contribute.

I'm a little wary of making any other change wrt the NA because I'm unclear when they would be. At first thought it was a ghost fleet thing but mine example doesn't have any NA's so I can't dig. Do you remember what you're expecting? I do think this will break if there are NA's so maybe at a minimum we could put in a warning if there are any?

**Comment by iantaylor-NOAA** [comment]
Sorry for the late follow-up @Cole-Monnahan-NOAA.
I was able to confirm that index observations excluded from the likelihood via a negative fleet numbers have NA in the $Like column, but don't recall any other reasons for NA values in that table.
In the interest of getting the bug fixed, go ahead make whatever change you feel confident about and we can worry about larger cleanup of that code some other time.

**Comment by Cole-Monnahan-NOAA** [comment]
I pushed this very small update to a separate branch and did a PR: https://github.com/r4ss/r4ss/pull/443

Let me know what you think.

I also noticed that the use of `par()` is inconsistent. I went through and made some changes to try to standardize the plots but I feel like that's maybe a bit much at the moment? Better done in a major overhaul?

You can reproduce this by running
````
mypar <- list(mar=c(3,3,1,1), mgp=c(1,.5,0), tck=-.01,
              col.axis='red',
              col.lab='blue', cex.lab=2)
SSplotComparisons(x, png=TRUE, par=mypar, new=FALSE,
                  plotdir='model_comparisons/test',
                  legendlabels=c('m01', 'm06'))
````

You'll see that some of the plots are affected but not others. I got this pretty close to very consistent with this commit: https://github.com/r4ss/r4ss/commit/652e98684273b7077c434197670c3ada5ee68741

I didn't do a PR for this one, but thought I'd put it up for judgement by the r4ss wizards.

**Comment by iantaylor-NOAA** [comment]
The changes all look good, @Cole-Monnahan-NOAA. Your second commit 652e986 got included in the original pull request which is just fine because the changes are most welcome. Thank you!

**Comment by iantaylor-NOAA** [comment]
This seems to have been resolved. Closing now. Thanks again for the help @Cole-Monnahan-NOAA.
