### ISSUE TITLE
replist$Growth_Parameters only returns female parameters

### ISSUE THREAD

**Issue by quang-huynh** [r4ss/r4ss#436]
I found another issue with a 2-sex model that reports two lines for Growth_Parameters in Report.sso (v 3.30), but the second line is missing coming out of `SS_output`.

**Comment by iantaylor-NOAA** [comment]
Another good catch, thank you @quang-huynh. This should be fixed in commit a9dd9a9 to `development`.

The `SS_output()` function got some cleanup back in June/July (discussed here: https://github.com/r4ss/r4ss/issues/9) and any errors in the read of tables like $Growth_Parameters which aren't used in any of the plotting code or included in any tests could have easily gone undetected, so I appreciate you posting these issues.
