### ISSUE TITLE
argument Natageplot of SS_plots is ignored

### ISSUE THREAD

**Issue by yukio-takeuchi** [r4ss/r4ss#464]
It appeared ,  Natageplot of SS_plots is not used . I suspect Natageplot is intended to disable to call  SSplotsNumbers but  SSplotsNumbers is always called regardless of value of Natageplot.

As my current model is 4 seasons model   assuming settlement occur each season and assignes different growth pattern to each season, SSplotsNumbers does not work correctly as it warns.
If I can skip calling SSplotsNumbers from SS_plots, I can obtain plots other htan N@A plots from SS_plots.

**Comment by iantaylor-NOAA** [comment]
Thanks @yukio-takeuchi for catching this, and sorry that the numbers-at-age plots aren't yet working for this type of model.

I'm sorry to say I have no memory of adding that option and looking at the "blame" view on GitHub, it appears that the input has been around an unchanged for at least the past 6 years: https://github.com/r4ss/r4ss/blame/development/R/SS_plots.R#L92.

The `SSplotNumbers()` function is called by `SS_plots()` as part of plot group 12: https://github.com/r4ss/r4ss/blob/development/R/SS_plots.R#L890-L923, so running 
```
SS_plots(replist = model, plot = c(1:11, 13:26))
``` 
should exclude those plots, which would seem to be a duplication of the intended functionality of the `Natageplot` argument (if we're correct about what it was supposed to do).

Therefore, rather than implement that argument, I think it would be better to just automatically skip any plots that fail for those models where they don't work and for cases where that's not enough, rely on the `plot` argument to skip any plot group as in the example below.

**Comment by yukio-takeuchi** [comment]
Thanks Ian. I forefoot to check plot argument. To me, excluding 12 in plot works fine.

Thank you so much
