### ISSUE TITLE
Keep comments starting from "#C" when dat/ctlfile is read by SS_readdat/ctl and write them in new dat/ctlfile by SS_writedat/ctl

### ISSUE THREAD

**Issue by yukio-takeuchi** [r4ss/r4ss#479]
SS allows users to put "data comments" on the lines starting from "#C" in datfile and ctlfile (may also be true for starter an forecast files. But I have not checked yet) . They are read as is by SS. Then SS writes them onto the head of data.ss_new and control.ss_new.

Currently SS_readdat and SS_readctl ignore them. Then SS_writedat and SS_writectl write their default data comments.
SS_writedat_3.30 writes 3 lines of default data comments. For example in my case
```
#C data file created using the SS_writedat function in the R package r4ss
#C should work with SS version: 
#C file write time: 2021-01-29 05:26:43
```

SS_writectl_3.30 writes 2 lines of default data comments. For example in my case 
```
#C file created using the SS_writectl function in the R package r4ss
#C file write time: 2021-01-29 05:26:43
```

These default information is of course useful. In addition.  If additional data comments written by user are also kept like what SS do, those additional data comments may also be useful, in particular, when user need to know what has been done by a particular dat/ctlfile.

I can make a quick changes to do so. But I would like to know how many data comments lines SS can read from dat/ctlfile. 
For example, from ctlfile that has following lines on the top
```
#V3.30
#C file created using the SS_writectl function in the R package r4ss
#C file write time: 2021-01-29 07:52:55
#C skj 2016
#C annualized
#C Test
#C Test2
#C Test3
#C Test4
#
#
#
#C Test5
```

SS creates control.ss_new with
```
#V3.30.16.00;_2020_09_03;_safe;_Stock_Synthesis_by_Richard_Methot_(NOAA)_using_ADMB_12.2
#Stock Synthesis (SS) is a work of the U.S. Government and is not subject to copyright protection in the United States.
#Foreign copyrights may apply. See copyright.txt for more information.
#_user_support_available_at:NMFS.Stock.Synthesis@noaa.gov
#_user_info_available_at:https://vlab.ncep.noaa.gov/group/stock-synthesis
#C file created using the SS_writectl function in the R package r4ss
#C file write time: 2021-01-29 07:52:55
#C skj 2016
#C annualized
#C Test
#C Test2
#C Test3
#C Test4
#C Test5
```

This suggests me SS allows and keeps  data comments anywhere in ctlfile

For datfile, data.ss_new was created similarly.

Does anyone has more information how many lines of data comments are allowed by SS and if data comments starting from "#C" can be put any lines of dat/ctlfile?

**Comment by Rick-Methot-NOAA** [comment]
I do not think there is any limit to the number of #C lines allowed.
As they are read, they are appended to an array.
There are four separate arrays:
  adstring_array Starter_Comments;
  adstring_array Data_Comments;
  adstring_array Control_Comments;
  adstring_array Forecast_Comments;
Then for ss_new, that array is written out in its entirety at the top of the appropriate file (data, starter or control) from which it was read.
It would be "nice" if they could be written out in the same location within the file from which they were read, but that would be a tremendous amount of programming.
A compromise could be to create a separate array for each section of each file, so for example, the data file could have catch comments, survey comments, length comp comments, etc.  Doing this would take the number of arrays from current 4, to 50 or so.  Then some programming so that when SS_read encounters a #C, it knows which section of the input file it was in.
Actually, this will be a lot of work.  Right now, SS reads the entire datafile to find all the #C lines.  
  k=0;
  N_DC=0;
  while(k==0)
  {
    Data_Stream >>  readline;          // reads the line from input stream
    if(length(readline)>2)
    {
      checkchar=readline(1);
      k=strcmp(checkchar,"#");
      checkchar=readline(1,2);
      j=strcmp(checkchar,"#C");
      if(j==0) {N_DC++; Data_Comments+=readline;}
    }
  }

Then it goes back to top of file and reads and processes the numbers and info.  So, during the first pass, SS has no idea which section of the file it is in.
Ahh, you could do it with another code.  So, #C1 would save to the first comment array, C2 for the second array, etc.  Then we could write out these arrays with the appropriate section of the output.

**Comment by k-doering-NOAA** [comment]
Thanks @Rick-Methot-NOAA! It sounds like SS doesn't have an explicit limit on the number of #C lines and that these lines can occur anywhere in the files, but will be written out in the .ss_new files at the header.

@yukio-takeuchi , thank you for suggesting this addition! I think it would be a useful feature to add, and if you are willing to work on it, that would be great. I'm happy to help out as needed, also.

It seems like it would be complicated to save the locations of #C comments in the R object, so I wonder if the same approach that SS takes (read in all #C comments from anywhere in the file, then write them out at the top), would also be fine for the r4ss::SS_read/write functions?

Like you pointed out, the comment lines generated by  look like:
```
#C file created using the SS_writectl function in the R package r4ss
#C file write time: 2021-01-29 07:52:55
````
I think maybe it is worth to continue appending these to the header, but I could be persuaded otherwise!

**Comment by k-doering-NOAA** [comment]
Update: Rick double checked and realized that actually all #C lines must be above the first model input in the file. Hopefully this simplifies reading and writing the comments in r4ss!

**Comment by yukio-takeuchi** [comment]
Thanks for all
I made a pull request for this.
