### ISSUE TITLE
convert tcltk functions to shiny?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#48]
Functions `movepars`, `selfit`, and `selfit_spline` all use tcltk package. The syntax is arcane and the package has some installation issues on some computers. Shiny may be an easier way to go for this type of function.

**Comment by allanhicks** [comment]
I started working on a shiny implementation for selectivity. How would you like me to upload this example? Shiny requires a folder containing server.R and ui.R, plus the call to invoke these. I'm not sure if we can have a single ui.R and server.R to invoke all the things we want, but that may be difficult to design the ui.

One thing I was thinking is to create a branch, and then a folder called Shiny in the top level (alongside the R and man directories). This would allow us to test Shiny for now and introduce it to the R library when ready.  Let me know if you have other ideas.

**Comment by taylori** [comment]
Allan,
Thanks for working on this.

It might be worth consulting with @seananderson on this as he understands better the folder structure required for R packages. It might be better to put the shiny-related stuff into an "extra" or "inst" folder as I believe that these are standard R package folders (at least they are present in https://github.com/ss3sim/ss3models which Sean just reorganized). In a branch it won't matter, but if it's easy to start out on the right path, that could save time later on.
-Ian

**Comment by seananderson** [comment]
`inst` is a standard package folder that is installed with the package and is accessible to the user through, say, `system.file()`. You can put any folder you want inside there as long as it doesn't match a folder name that already has special properties (`doc` is an example of that, since it houses the rendered vignette files).

`extra` isn't a standard folder, but it's an example of how you can add any folder you want at the root level as long as you add it to the `.Rbuildignore` file. Otherwise, `R CMD build` will issue a warning about a nonstandard folder. This, of course, means that it's not accessible in the loaded package.

I don't have much experience with Shiny yet, but one option that seems to work well for cases where the level of website customization is minimal and the output is more report-like is to [embed the Shiny code into an R Markdown document](http://rmarkdown.rstudio.com/authoring_embedded_shiny.html). This saves you from having to deal with separate `.R` files and takes care of the web layout side of things. You'd render that into an HTML file with `rmarkdown::render()`.

I imagine that eventually you'd have code in functions within the `R` folder that when called renders an HTML page with Shiny embedded. Not sure where it would be best to house any template files you need, but somewhere in the `inst` folder might make sense.

**Comment by allanhicks** [comment]
THanks guys.  I created a branch called Shiny_ach with a Shiny folder in inst.  Try this code (you may have to load the shiny library).

devtools::install_github("r4ss/r4ss", ref="Shiny_ach")
#library(shiny)
selShapes <- function() {
	d <- system.file("Shiny", package = "r4ss")
	runApp(file.path(d,"Selectivities"))
}

There is an issue with the double normal code, but the concept is there, I think.  Feel free to modify or suggest ways to improve the code or folder structure, etc.  I realize that there is a lot of cleanup and documenting, but hopefully this is a good start.

Allan

**Comment by taylori** [comment]
Hi Allan,
Installing the shiny package and loading and running your branch https://github.com/r4ss/r4ss/tree/Shiny_ach/ following your instructions worked just fine for me (aside from double normal not updating). The interface is smoother and easier than the Tcl/Tk version. Perhaps there could be a button or switch to turn on the -999 option for the 5th and 6th parameters instead of having a huge range like the old version. Assuming this eventually replaces the old version, you could give Tommy Garrison credit as a co-author since his legacy will be living on.

Running it in Emacs, it wasn't clear how to close the shiny app. It just said "Listening on http://127.0.0.1:6763" even after I closed the browser window until I shut down the Rterm process. But we can work that out some other day when we have more time. For now I will just test future iterations in the Rgui or in RStudio.

-Ian

**Comment by taylori** [comment]
Adding follow-up note about recent discussion with @seananderson 
Putting a Shiny version of `selfit_spline` on a Shiny Server or shinyapps.io would improve useability by no longer requiring installation or compiling of an ADMB executable.

**Comment by taylori** [comment]
Additional benefit of moving away from tcl/tk to Shiny is that new continuous integration tool has problems with tcltk:
https://travis-ci.org/r4ss/r4ss

**Comment by seananderson** [comment]
I'd forgotten that issue with r4ss and tcl/tk was what stopped me from updating the ss3sim Travis build script. In the meantime you should be able to copy this older config file https://github.com/ss3sim/ss3sim/blob/master/.travis.yml  which builds the whole kitchen sink each time.

**Comment by taylori** [comment]
Thanks @seananderson 
We'll see if that works. I just copied your file wholesale in 330887c5724fddea828c9d236c6888492c95f5fc so if some refinement was needed, feel free to edit it yourself.

**Comment by taylori** [comment]
No luck:
https://travis-ci.org/r4ss/r4ss

```
Running command: bootstrap
...
+sudo add-apt-repository 'deb http://cran.rstudio.com/bin/linux/ubuntu precise/'
sudo: must be setuid root
The command "./travis-tool.sh bootstrap" failed and exited with 1 during .
```

**Comment by taylori** [comment]
As noted in comment on pull request #109, the issue with Travis-CI seems to have been sorted out.
Replacing Tcl/Tk with Shiney as suggested in the initial description of this issue would still be useful but is not necessary for getting the Travis-CI automatic package checking to work.

**Comment by taylori** [comment]
Recent commit 3237397 has tcltk package suggested but not required. Users wishing to use selfit and selfit_spline functions need to install manually. Moving to shiny would still be useful.

**Comment by taylori** [comment]
Thanks to a query from @mkapur-noaa, I'm reminded that the locations of the materials related to the `selfit_spline` function which relied on tcl/tk have moved out of the `r4ss` package. 

There's a Windows executable and a TPL file that could be compiled for other systems in the repository https://github.com/r4ss/testing/ (which is a disorganized collection of old and unfinished things) while the `selfit_spline.R` function was moved from the main `r4ss` repository to the `old_r4ss_files` repository: https://github.com/r4ss/old_r4ss_files/blob/master/selfit_spline.R.

It's possible that the best approach would be to create an entirely new R package for the selectivity explorations functions, possibly based on Shiny such as being developed in the `Shiny_ach` branch of r4ss recently contributed to by @Andrea-Havron.

**Comment by Andrea-Havron** [comment]
Thanks @taylori for merging my edits to the ui.R file in the Shiny_ach branch. I also made changes to the server.R file which need to be merged for the app to work. I'm also hoping others can play with the double normal settings to make sure plots are drawing correctly.

**Comment by taylori** [comment]
Thanks again @Andrea-Havron for working on this. It might be necessary to post some instructions (such as those above: https://github.com/r4ss/r4ss/issues/48#issuecomment-75469668) on how to run the Shiny server in order for people to try this out. It may also require adding Roxygen comments to the top of any new functions, including `@export` as seen in the other `r4ss` functions and then running `devtools::document()` on the `Shiny_ach` branch of the package and pushing the changes to `NAMESPACE` which should now include the new functions.

I just attempted to rebase the `Shiny_ach` onto `development`, so that if users install it for exploration of these changes, they wont' lose all the other functionality of the package. @Andrea-Havron this may mess up your Patch-3 branch of the branch which would also need to catch up.

And now it's late on a Friday so I'm walking away from this (and sadly need to focus on other things next week).

**Comment by allanhicks** [comment]
I updated the Shiny functions for selectivity functions (#283) in the Shiny_ach branch. Many thanks to @Andrea-Havron for getting the double normal to work. I updated the ui and server so that the user can enter parameters via a slider bar or enter them in directly into a box. The two will mirror each other.  A lot of work could be done on the user interface and adding other selectivity options.

Simply call `selShapes()` and it should work if you have the shiny library installed. If not it will give you a message to install and load the shiny library:
`install.packages(shiny)`
`library(shiny)`

I'm not sure if the Shiny library should be a part of r4ss package or an entirely different implementation could be done. I see three options (and open to other options):

1. keep it as is where the user must install the shiny package on their own,
2. bring the shiny library into r4ss,
3. completely separate the shiny libraries from r4ss and host them on a web server (_As posted by @taylori in https://github.com/r4ss/r4ss/issues/48#issuecomment-109092018_)

**Comment by taylori** [comment]
Thanks @allanhicks and @Andrea-Havron for making this happen.

Installing the branch with these changes via 
```
devtools::install_github('r4ss/r4ss', ref='Shiny_ach')
```
and then running `selShapes()` indeed worked and started the shiny app in the figure below. It didn't run using Rterm within Emacs, but that's not a big deal.

In commit 5439505286a359a2b6a80a3b8c3792389ecb25fb I just moved forward with a blend of 1 and 2 which is to add shiny to the list of suggested dependencies in DESCRIPTION. There are some suggestions here http://r-pkgs.had.co.nz/description.html#dependencies for how to add a check to the functions that depend on packages in `Suggests` which might be good to add to the `selShapes` function.

I think in the long run, it would be better to switch to option 3 (separate the shiny apps from the rest of r4ss either hosted on a server or as an independent package), especially if the cubic spline selectivity with dependency on an ADMB executable were included.

If anyone else has time to try this, please comment here and we can merge into the main r4ss trunk if there aren't any installation issues.

![image](https://user-images.githubusercontent.com/4992918/56172369-fff10300-5f9d-11e9-8585-7b144b42729b.png)

**Comment by k-doering** [comment]
@taylori  I was able to install the branch from github and run ```selShapes()``` on a Windows 10 computer. This is a cool tool, thanks @Andrea-Havron and @allanhicks!

Looks like there isn't documentation for the function yet, though? I don't know what is typically done for shiny apps, but perhaps adding a short description would be useful?

**Comment by allanhicks** [comment]
Good point @k-doering and thanks for testing. The ui could use a lot of work, but a simple explanation or help page would be useful. 

Note, that to return your r4ss package to the most recent version from the master branch you may want to run 

`devtools::install_github('r4ss/r4ss')`

after testing. 

Also, @pieracarpi tested the shiny app in Rstudio and it worked. Thanks Piera.

**Comment by akatan999** [comment]
I also tested it and it works on my windows 10 machine

Max

**Comment by taylori** [comment]
I accidentally removed selShapes from NAMESPACE by running `devtools::document()`. Adding `@export` to the Roxygen comments in `selShapes.R` in commit 4b9457ba2a89154447a0693411a6407a714f4237 allowed `devtools::document()` to add it back.

**Comment by k-doering-NOAA** [comment]
Closing, as the shiny app has been around for a while now and is no longer housed within r4ss.

**Comment by iantaylor-NOAA** [comment]
Not sure why this issue is still open.
