### ISSUE TITLE
mcmc nuisance default includes "iter" and "objective function" in summary statistics

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [r4ss/r4ss#488]
The default labelstings = "all", which I suspect is quite commonly used as most often you want to look at all parameters, should automatically not include columns "iter" and "objective function" as there is seemingly no purpose for those in summary statistics. When using the default you will get "no test" for the heidelwelsch test and meaningless effN, geweke, and autocorrelations.

**Comment by iantaylor-NOAA** [comment]
Good idea, @aaronmberger-nwfsc. This should be fixed in commit 0e11f602db7238db5de9a26cb6675019cc0e683c to the `development` branch. I think this function is really only used by the hake team these days, so please suggest any other changes you think would be useful. 

Note, we can also explore someday switching to the `plotMCMC` package (as discussed in issue #25).
