### ISSUE TITLE
SS_output printed MI data weighting not output

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [r4ss/r4ss#489]
The SS_output prints out diagnostic information to the terminal by default.  In the $Age_Comp_Fit_Summary output the Recommend_var_adj printing out 1.0 incorrectly.  I am working with the most up to date version in the development branch.  I thought we (we meaning Ian) had corrected this problem. Is this correction in a different branch or has this not been corrected yet?

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA fixed the `SS_tune_comps()` function in this commit: https://github.com/r4ss/r4ss/commit/0d2614beb5549697052edaf55a457944659fce58
and the underlying problem has now been fixed in Stock Synthesis so the next SS release (maybe next month) will have the correct value in the table that gets read by r4ss. But it looks like `SS_output()` isn't fixing anything for SS version 3.30.16. Will the correct value in SS_tune_comps() work for your purposes?

**Comment by chantelwetzel-noaa** [comment]
Thanks @iantaylor-NOAA.  I remember you saying it was fixed and was surprised that I was still seeing the 1.0.  Clearly I missed the fact that the underlying issue was in SS reporting and not in the internal r4ss code.  The SS_tune_comps() function is working and has been how I have been getting these values.
