### ISSUE TITLE
Suppression of initial equilibrium plotting

### ISSUE THREAD

**Issue by IJStewart** [r4ss/r4ss#51]
For both SS_plots and SSplotComparisons it would be helpful in some circumstances to have an argument to suppress the plotting of the initial equilibrium biomass estimates.

**Comment by iantaylor-NOAA** [comment]
This issue was resolved by @colemonnahan in November 2015 by adding the `show_equilibrium = TRUE/FALSE` input to `SSplotComparisons`: 5e61114aeca20f4beae60fc5726b9b6b2261afed.

One reason to avoid plotting the equilibrium values is if you don't care about them and want them off the figure. However, another is when you have different starting years and they were displaying incorrectly. 

For reasons that I no longer remember, the `SSsummarize` function was shifting the equilibrium values associated with `VIRG` and `INIT` to appear at `startyr - 2` and `startyr -  1` which could cause an ugly plot like the one below
![equilibrium_bad](https://user-images.githubusercontent.com/4992918/74263516-d84cf300-4cb3-11ea-89f0-1170f62a4d20.png)
In commit 0e89536 to the `development` branch I've just modified `SSsummarize` to remove that shift so the equilibrium values all appear in the same place at the far left as below. If anyone misses the old functionality please speak up and we can add it back with a switch or the like.
![equilibrium_good](https://user-images.githubusercontent.com/4992918/74263638-11856300-4cb4-11ea-9889-d2d80324e804.png)
