### ISSUE TITLE
update label(s) in SS_Sensi_plot.R

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [r4ss/r4ss#518]
1. I believe the report label for the derived management quantity 'Fstd_SPR' has now changed to 'annF_SPR' and thus needs to be updated in this new function feature.  Excellent to have this part of the package now - just operationally used it!

2. A potential improvement for consistency: match the spawning output definition/metric used in SS_plots (default is a 'Spawning Biomass' label I think) with the one used in SS_Sensi_plot which is hard coded to use SO instead of SB.

**Comment by iantaylor-NOAA** [comment]
Thanks @aaronmberger-nwfsc.
For the first item, I think it would work to change from
`model.summaries$quants$Label == "Fstd_SPR"`
to
`model.summaries$quants$Label %in% c("Fstd_SPR", "annF_SPR")`
to support backwards compatibility for older versions of SS since no model should have both labels.

On the second point, model.summaries$SpawnOutputUnits will either be a single value of "biomass" or "numbers", or a vector if the models don't share the same units. My suggestion would be to change "SO" to "SB" in cases where `all(model.summaries$SpawnOutputUnits == "biomass")`, and stick with "SO" otherwise. Does that make sense?

@shcaba please chime in with any input on this.

**Comment by aaronmberger-nwfsc** [comment]
ah, yes I forgot about the Output units now being tracked explicitly.  Your suggestions look perfect to me.

**Comment by aaronmberger-nwfsc** [comment]
One other label thing that has come up (and thanks to @chantelwetzel-noaa for input on this) is changing the current figure label of 'MSY[SPR]' to something more explicit, like 'Yield (SPR=0.3)' (case for Dover sole, but could be generalizable using the forecast file inputs) or 'Yield (tgt SPR)' or something similar.  Thoughts [@shcaba](https://github.com/shcaba)...?  This sort of explicit, though generalizable, definition could apply to the 'F(SPR)' label as well, such as 'F (tgt SPR)' or F (SPR=0.3).

**Comment by iantaylor-NOAA** [comment]
I've attempted to implement these changes in commit d51fd9d in the `sens_plot_issue_518` branch, where the labels will be created dynamically by default but there are new arguments (`spawn.lab`, `yield.lab`, and `F.lab`) to override those defaults (e.g. `spawn.lab = "B"` to get "B0" instead of "SB0"). Results for simple test are below.

Install via
`remotes::install_github("r4ss/r4ss@sens_plot_issue_518")`
and please report any issues or further suggested changes.

Note: a change for the future would be to give folks working in regions which don't use SPR-based reference points a way to use other quantities.
![Sensi_logREplot_all](https://user-images.githubusercontent.com/4992918/114628099-30420980-9c6b-11eb-8665-bc2fe4513d7d.png)

**Comment by iantaylor-NOAA** [comment]
The revised code seems to be working, so merging this change to clean up branches.
Revised code now available in main branch via `remotes::install_github("r4ss/r4ss")`.
Original author of this function Jason Cope (@shcaba) has been on vacation so he can comment on these changes after returning.
