### ISSUE TITLE
error when using SS_tune_comps()

### ISSUE THREAD

**Issue by shcaba** [r4ss/r4ss#532]
I am now getting the following warning:
Warning: Error in .rowNamesDF<-: invalid 'row.names' length

Not sure if anyone else is getting this. Using the same function call I have been using for a while now.
I am happy to provide the offending model run if needed.

**Comment by shcaba** [comment]
Found the issue. The SS data file had an error, but still ran fine, though failed in the data-weighting loop.

**Comment by iantaylor-NOAA** [comment]
Thanks @shcaba for reporting this and finding the problem.

Coincidentally (I think), I was just sent a model that had this same error but tracked it down to duplicate entries in the lambda section of the control file, where SS seems to have just replaced the first entry with the second one.

`SS_tune_comps()` reads the data and control files as part of the newer option to automatically modify those files and iterate the tunings thanks to @k-doering-NOAA. However, that makes the function more fragile. We should find a way to help users zero in on the input file issues (which are useful to find) rather than having it appear as if the tuning function is the problem.

**Comment by iantaylor-NOAA** [comment]
I created issue #533 with a suggestion for how to deal with this issue in a better way, so closing here.
