### ISSUE TITLE
run_SS_model not working with exe in path

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#567]
Thanks @Rick-Methot-NOAA for discovering this. After adding Stock Synthesis to the PATH, it is not working through run_SS_models.

```r
SS_exe_path <- "C:/Users/my.computer/path/to/exe"
system("PATH", input = "%PATH%,SS_exe_path")
# [1] 127
r4ss::run_SS_models(dirvec = dir, model = "ss", exe_in_path = TRUE,
                     skipfinished = FALSE)
#Error in r4ss::run_SS_models(dirvec = dir, model = "ss", exe_in_path = TRUE,  :
# Exe named ss.exe was not found in your PATH.
```

**Comment by kellijohnson-NOAA** [comment]
I think you have to augment your path using `Sys.setenv("PATH")` within an R session. If you temporarily augment the PATH variable using `system` R would have to be restarted to change the Path it sees, but that defeats the purpose because the change to the path doesn't exist beyond that local R window.

**Comment by Rick-Methot-NOAA** [comment]
That is what I tried to do with:

SS_exe_path <- "C:/Users/my.computer/path/to/exe"
system("PATH", input = "%PATH%,SS_exe_path")


*Richard D. Methot Jr. Ph.D.**NOAA Fisheries Senior Scientist** for Stock
Assessments*

*Mobile: 301-787-0241*

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA would the right commands be:

```r
SS_exe_path <- "C:/Users/my.computer/path/to/exe"
system("PATH", input = "%PATH%,SS_exe_path")
Sys.setenv("PATH")
r4ss::run_SS_models(dirvec = dir, model = "ss", exe_in_path = TRUE,
                     skipfinished = FALSE)
```
?

**Comment by iantaylor-NOAA** [comment]
Just to clarify, I'm assuming that the function works if the PATH is defined outside of R prior to starting the R session, where the problem here is as @kellijohnson-NOAA suggests that the modification of the PATH within R isn't getting through. Let me know if I'm understanding that wrong.

@Rick-Methot-NOAA, your solution seems like the easiest one for cases where you want to dynamically specify an exe location that isn't already in the PATH. If that seems adequate and my understanding above is correct, then it seems no change to the function is needed.

And yes, you can use the `extras` input to add additional command-line arguments, like
`run_SS_models(dirvec = dir, model = SS_exe_path, skipfinished = FALSE, extras = "-nohess")`

Also, note the `intern = TRUE/FALSE` input which lets you choose between seeing all the command-line information appear in your R session or sending it to a text file.

**Comment by Rick-Methot-NOAA** [comment]
I believe a permanent change to PATH would work and be recognized by R
but procedure to make that PATH edit is too cumbersome for a class
exercise, so I was trying for an easy temporary change to PATH.
thanks for info on extras
all working now
