### ISSUE TITLE
Correct documentation for `copy_SS_inputs()` @return

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#600]
https://github.com/r4ss/r4ss/blob/49d36f04aa79a504bb5904a77c82c570301d536d/R/copy_SS_inputs.R#L19

It returns a logical.

**Comment by kellijohnson-NOAA** [comment]
I was hoping that it was returning the path to the new folder, I am not sure if this would be an option or not? Not worth changing if downstream code depends on the logical.

**Comment by k-doering-NOAA** [comment]
I think it would be fine to change it, that seems a lot more useful.

**Comment by iantaylor-NOAA** [comment]
I agree with @k-doering-NOAA, I don't think there would be any negative impact of a change like that. We could also make it return invisibly if that would be better.
@kellijohnson-NOAA, is your suggestion to return the full path so that if `dir.new = NULL` or a relative path then it would return the working directory plus that path?

**Comment by kellijohnson-NOAA** [comment]
I hadn't thought that far 😉 I think I was thinking it would just return whatever was input into `dir.new` but then what is the point of outputing an input? Clearly I posted an issue because I don't really know what is best but wanted to at least have the documentation match what was being done. Maybe we should just leave it as is and I can just store the value being supplied to dir.new as an object before passing it to the function.

**Comment by iantaylor-NOAA** [comment]
Sounds like a reasonable solution, @kellijohnson-NOAA. I've just updated the documentation in 3f4293f. Feel free to reopen or revise further as you see fit.
