### ISSUE TITLE
deprecate or clarify SS_splitdat()?

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#624]
I'm wondering what should be done with SS_splitdat() given the data output files will be split into separate files in 3.30.19?

It makes some sense to keep it around for historical reasons (because people will continue to use older version of ss3 models for some time), but perhaps we should add documentation to make it clear that this function is not needed for .19 and higher versions.

**Comment by kellijohnson-NOAA** [comment]
Thanks @k-doering-NOAA for making this an issue. imo we should soft deprecate it because we will want to give users some fore warning that it is not being maintained and, in the future, will not be available. Will we need to keep around some truncated version of it going forward to allow for the reading of input and output files so results can be compared? I do not think so but I have not looked at the code to confirm.
