### ISSUE TITLE
default of SS_writectl @version is not the same as the default of SS_writedat @version

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#641]
https://github.com/r4ss/r4ss/blob/17a16966e786820081685b05164f70656457b65e/R/SS_writectl.R#L23 defaults to NULL which then leads to r4ss attempting to determine the version. Where, `SS_writedat(version = "3.30")`. All other functions with the version argument have `version = NULL`. I am really not sure on which option is the best but I think having one default would be good.

**Comment by iantaylor-NOAA** [comment]
I'm think that in the past it made sense to have these functions be smart where possible and figure out which version to use, but at this point, the use of version 3.24 should be so rare that anyone still doing can be asked to be really explicit about it.

I see `version = "3.30"` inputs for: `SS_output()`, `SS_parlines()`, `SS_profile()`, `SS_readforecast()`, and `SS_varadjust()`, whereas I only see `version = NULL` in `SS_writectl()`, `SS_readctl()`, and `SS_readdat()`.

It seems reasonable to change NULL to "3.30" in those three cases as long as we also add a warning when there's evidence that this might be wrong (e.g. modify the lines below to warn if `ctllist[["ReadVersion"]]` doesn't match the input:
https://github.com/r4ss/r4ss/blob/17a16966e786820081685b05164f70656457b65e/R/SS_writectl.R#L36-L39

**Comment by kellijohnson-NOAA** [comment]
Great, I didn't want to specify a preference in my original issue, but having `version = 3.30` as the default will simplify code in {ss3sim}.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA would you like me to submit a pull request for this?

**Comment by iantaylor-NOAA** [comment]
Yes, that would be awesome. Thank you.

**Comment by kellijohnson-NOAA** [comment]
Should the use of `version` be removed when calling `SS_readdat(version = "3.30")` within `SS_output()`?

https://github.com/r4ss/r4ss/blob/17a16966e786820081685b05164f70656457b65e/R/SS_output.R#L1457-L1460

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, good questions.
* Regarding `SS_output()`: yes, remove the `version` input now that the default is provided by `SS_readdat()` instead. That line will only be called for 3.30 models anyway because DM parameters didn't exist in 3.24.
* Regarding `SS_profile()`. Given that the default input is already been "3.30", the only folks providing that input explicitly are those running profiles in 3.24, which hopefully isn't happening at all. So I would just change to `version` and not bother with lifecycle. `SS_profile()` doesn't use `...`, so anyone providing `SSversion` would get an error that should be adequate to sort out the problem. But if you feel like using lifecycle, go for it. There are examples in many other r4ss functions.

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA should `version = NULL` remain supported in the functions? Also, sorry for all the questions but figured it was easier to ask now.

**Comment by kellijohnson-NOAA** [comment]
Closed with [b1137f9](https://github.com/r4ss/r4ss/commit/b1137f9c4834a08fd6d52fd2f281bf4dbc25fa87).
