### ISSUE TITLE
Possible issue with make.phase.plot.MLE within SSplotSPR

### ISSUE THREAD

**Issue by careymcg** [r4ss/r4ss#654]
Looks like there's a mismatch between naming conventions in make.phase.plot.MLE that is making the function choke. Looks like vec and val should be vectors and values: 

![image](https://user-images.githubusercontent.com/4474981/163885227-1b0b1e0a-b9b2-4845-a971-a3f7cf8eaf5d.png)

![image](https://user-images.githubusercontent.com/4474981/163885265-885df0ab-60e7-4310-a630-846b4c0ae0c0.png)

**Comment by iantaylor-NOAA** [comment]
Thanks for reporting this @careymcg. This one was easier than the other (#653).

The original code used `$` (which is problematic because of partial matching), but the `rm_dollar_sign()` function is now run as part of the github actions thanks to @k-doering-NOAA. In this case, the original code used partial matching so it stopped working when that was no longer allowed.

It should now be fixed in [e24a525](https://github.com/r4ss/r4ss/commit/e24a52549479c5fa1c9fdb6339f702e6a29056a5).
