### ISSUE TITLE
consider renaming some instances of lwd  to lwd_vec

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#693]
While working on #311 , @kellijohnson-NOAA and I realized that sometimes there were parameters with the same names, but different definitions, e.g., `lwd`. `lwd` has a template now, but some instances of `@param lwd` were not changed in the documentation because they expected vectors instead of a single value, so their definition differed from the definition in the template.

Perhaps we should change the `lwd` instances that expect a vector to something like `lwd_vec` to make it a little more clear that they are different? `lwd` could be soft deprecated, then removed upon the next release. 

Here are the instances of @param lwd in the code currently (with the first being the template definition):

```
man-roxygen\lwd.R:
  1: #' @param lwd Line width for plot elements.

R\helper_fxns.R:
  137  #' @param lty Optional vector of line types
  138: #' @param lwd Optional vector of line widths
  139  #' @param type Type parameter passed to points (default 'o' overplots points on

R\PinerPlot.R:
  34  #' @template lwd
  35: #' @param lwd.total Line width for the total likelihood.
  36  #' @param cex Character expansion for the points representing the likelihood

R\SSplotComparisons.R:
  76  #' @param lty Optional vector of line types
  77: #' @param lwd Optional vector of line widths
  78  #' @param spacepoints Number of years between points shown on top of lines (for

R\SSplotDynamicB0.R:
  29  #' (single value will apply to both lines).
  30: #' @param lwd Optional vector of line widths to be used for the two lines.
  31  #'  Single value will apply to both lines.

R\SSplotProfile.R:
  40  #' @param lty.total Line type for the total likelihood.
  41: #' @param lwd Line width for the likelihood components. 
  42: #' @param lwd.total Line width for the total likelihood.
  43  #' @param cex Character expansion for the points representing the likelihood
```

**Comment by iantaylor-NOAA** [comment]
In base R, the `lwd` argument can either be a single value that gets recycled as needed or a vector as described here from ?par:

> The line width, a positive number, defaulting to 1. The interpretation is device-specific, and some devices do not implement line widths less than one. (See the help on the device for details of the interpretation.)
> 
> Functions such as [lines](vscode-webview://1kvlu81rsntohtrs9u32b9gle2n0jpn3817gnoh6ul2qnhsthu65/graphics/help/lines) and [segments](vscode-webview://1kvlu81rsntohtrs9u32b9gle2n0jpn3817gnoh6ul2qnhsthu65/graphics/help/segments) accept a vector of values which are recycled: in such uses lines corresponding to values NA or NaN are omitted. The interpretation of 0 is device-specific.

I like the idea of just a single `lwd` argument across the functions that gets interpreted however is appropriate for the plot rather than separate arguments when it's a single value or a vector.

I regret the use of arguments like `pwidth`, `pheight`, and `ptsize` that don't match the `width`, `height`, and `pointsize` that are used in base R graphics when the r4ss arguments are simply passed to those other parameters. However, the r4ss arguments have been around since the beginning so I'm not sure it's worth the disturbance of aligning them now.
