### ISSUE TITLE
Coda Package with R version 3.2.2

### ISSUE THREAD

**Issue by CWetzel** [r4ss/r4ss#72]
The coda package which r4ss currently requires has not been built for the latest R version.

**Comment by allanhicks** [comment]
The installation of r4ss in R 3.2.2 worked fine for me.  They must have updated coda.  To avoid these difficulties in the future, we may be able to code in less dependency on outside packages, or call update.packages to make sure that other packages are up to date.

**Comment by taylori** [comment]
Thanks for the update. Happy that it worked.

@seananderson has been helpful in refining the dependencies for r4ss. I think running update.packages would be overkill and probably raise some flags on CRAN but we may be able to refine the dependencies for rarely used functions like those from coda which are only used by the mcmc.nuisance and mcmc.out which few r4ss users use.

Thanks to Sean, Instead of requiring whole packages, in many cases, r4ss calls out individual functions from other packages (see instances of "importFrom" in NAMESPACE: https://github.com/r4ss/r4ss/blob/master/NAMESPACE). However, with coda, enough functions are required that naming them all didn't make as much sense.

**Comment by taylori** [comment]
Haven't seen further problems with coda so closing the issue.
