### ISSUE TITLE
[Bug]: Error in reading in composition data

### ISSUE THREAD

**Issue by lidach** [r4ss/r4ss#756]
### Describe the bug

When I try to read in the SS model using SS_output, an error is produced when reading in the model and the composition data part (in picture).

### To Reproduce

I am using this folder with black sea bass:
https://github.com/gavinfay/bsb-ss-2022

I used SS_output, which produced the error.

### Expected behavior

The model does have length and age (age at length) compositon data to read in, so there should be no errors when using SS_ouput.

### Screenshots

![image](https://user-images.githubusercontent.com/32689355/200434451-75b4690b-4c04-4925-a816-b6c6af78a251.png)

### Which OS are you seeing the problem on?

Windows

### Which versions of r4ss and SS3 are you seeing the problem on?

r4ss 1.46.1
SS 3.30.20

### Additional Context

I think it has to do something with the names of some variables being read from the composition sections of the Report.sso file, like HarMean(effN) vs HarMean_effN; MeaneffN/MeaninputN vs mean_effN (hopefully I'm not missing any others here). I replaced some of the variables names and that made the SS_output function work.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by iantaylor-NOAA** [comment]
Hi @lidach,
Sorry for the error. Unfortunately I wasn't able to replicate the problem.
I downloaded the model files from github, ran with the SS3 version 3.30.20 release, reinstalled r4ss from github, and `SS_output()` was able to read the model results.

Based on past experience with puzzles like this, I think that the most likely scenarios are that either your version of r4ss is slightly out of date either because your most recent installation didn't work correctly or because there has been a fix implemented without a change in the package version number. To help diagnose that possibility, I've just incremented the version number from 1.46.1 to 1.46.2 (which should have been done a while ago given a variety of changes that have taken place in the past 3 months since the last version change).

Can you reinstall r4ss from github, confirm that you have version 1.46.2 (which may require restarting R), and then try `SS_output()` again? Please report back here whatever you find out.

**Comment by lidach** [comment]
Hi @iantaylor-NOAA, I reinstalled r4ss v. 1.46.2 and it worked. I thought I did reupdate the package, but it probably did not install properly.

Thank you so much for your quick response and help!

**Comment by kellijohnson-NOAA** [comment]
For more info on this issue, I am guessing that @lidach you had the CRAN version of r4ss installed, i.e., 1.44.0 because I just ran into the same trouble. The problem is coming from `r4ss::SS_output()` on the following line 
https://github.com/r4ss/r4ss/blob/8526f77597c8a7db5cd9d2a737876257d2cf3451/R/SS_output.R#L2240
because the names of `agentune` are 
```
 [1] "Data_type"         "Fleet"             "Recommend_var_adj"
 [4] "#"                 "Nsamp_adj"         "Npos"             
 [7] "min_Nsamp"         "max_Nsamp"         "mean_Nsamp_in"    
[10] "mean_Nsamp_adj"    "mean_Nsamp_DM"     "err_method"       
[13] "err_index"         "par1"              "val1"             
[16] "par2"              "val2"              "mean_effN"        
[19] "HarMean_effN"      "Curr_Var_Adj"      "Fleet_name" 
```
but the old code is expecting the first column to be named `"Factor"` and thus it goes into the else statement and ends up on line 2240 where the column `"MeaneffN/MeaninputN" does not exist.

I think that this is a good reason to update the CRAN version.
