### ISSUE TITLE
Development workflow for r4ss

### ISSUE THREAD

**Issue by colemonnahan** [r4ss/r4ss#77]
@taylori, is there a desired workflow for contributing to r4ss? For instance, in ss3sim we use branches for most changes (https://github.com/ss3sim/ss3sim/wiki/Git-Workflow). I think it's been helpful to have us all working under the same set of workflow rules.

Does something like this exist for r4ss? At what point should I create a branch vs. using master? Do you want us to automatically merge in branches or let you handle the pull requests? If I do something bigger, should I work on a forked repo?

**Comment by taylori** [comment]
Good question @colemonnahan 
There is not yet a desired workflow, or at least not yet anything written down. Using https://github.com/r4ss/r4ss/wiki as the ss3sim project did to put suggestions in place makes sense.

Unlike ss3sim which was a very collaborative process from the outset, the group of active r4ss contributors has grown more slowly and at many times in the past been just me.
I've approved pull requests after looking over changes that others have made in branches which has worked well. I've typically made my own contributions in the trunk but there would probably be a benefit to me using branches as well.

We could get more sophisticated on testing as well, perhaps in conjunction with testing SS itself, but such goals shouldn't stand in the way of short-term progress.

@amart has worked in a forked repo that she's using for a specific project but otherwise this hasn't been done.

**Comment by taylori** [comment]
I don't have any grand ideas for r4ss workflow but welcome input.
This note is just to state that starting today I will attempt to use branches for future changes rather than always modifying the trunk.

**Comment by taylori** [comment]
@allanhicks @James-Thorson and I have just begun an email conversation about r4ss workflow that I'm switching to GitHub so that others can be aware of the discussion and contribute if they wish.

I've just created a Wiki page to describe the recommended r4ss Git Workflow once we have a better sense of what it is: https://github.com/r4ss/r4ss/wiki/Git-Workflow

Here are a few guiding principles that I would suggest we follow:

- Have a lead package maintainer but also have other contributors who are willing to step in when things need to get done and the lead person is unavailable. I'm happy to continue in this role but am open to negotiations about that.
- Allow any r4ss users to become a member of the project on GitHub if they are interested.
- Be welcoming to suggestions and contributions in many forms (including to this list of principles).
- Allow anyone contributing a new function to be lead author of that function and manage future edits and retain some control over the coding style and aesthetics of any figures that are created.
- Encourage contributors to follow Hadley Wickham's R style guide: [http://adv-r.had.co.nz/Style.html](http://adv-r.had.co.nz/Style.html). Most of the existing code generally follows this style with the exception of the object names, which are a mess.
- Encourage the use of branches and pull-requests but not let confusion about that process stand in the way of progress especially when a simple change to the trunk is not likely to break anything important.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA , a specific workflow question that may apply to others:

I am currently working in a feature branch I created off my forked r4ss development branch.  I was wondering if documentation is changed in some way (either because of creation of a new function or editing), would you prefer that I run ```devtools::document()``` and commit the changes in the feature branch before submitting a pull request to the r4ss development branch? Or would you prefer that the documentation be updated after the merge occurs? Or does it matter very little?

**Comment by iantaylor-NOAA** [comment]
Thanks for asking. I think that it matters relatively little, but I would slightly prefer the second option because the documentation is more likely to get changed right away. In cases where changes to the .R files have been merged without the associated change to the .Rd file, the mismatch usually doesn't get noticed until `devtools::document()` gets run for some other reason later on, in which case the commit history is a little mixed up between the change to the code and the change to the documentation. Also, I think it's good if someone can install a branch of the package and have the documentation be internally consistent within that branch.

Having said all that, it's not a big deal regardless of how you do it--I'm just happy to have folks contributing.

**Comment by k-doering-NOAA** [comment]
Thanks, Ian! So, are you saying to update the documentation on the feature branch before submitting a pull request, then? Or that the person (likely you) reviewing and deciding what changes to keep from the pull request would then document() and commit changes after the feature branch has been merged in to ensure that the documentation is consistent with the code? I think you described the latter, but wanted to check. (and I guess doing both is also a possibility, but will increase the number of commits that are just updating documentation)

I also agree that making sure to run document() after merging in a feature branch is probably the best way to make sure the documetation is consistent with the code.

Thanks a lot for your insight on this!

**Comment by colemonnahan** [comment]
I don't remember putting this up but it flagged me so I'll chime in. 

It seems best to have the person document() and even do the package checks in devtools before merging in. Then if they introduce a subtle issue someone down the line won't have to track it down when going to submit to CRAN. This is assuming that r4ss master can also pass those tests. But that seems like a good idea in general, to encourage (force) contributors to check they haven't introduced anything illegal from CRAN's perspective.

**Comment by k-doering-NOAA** [comment]
Thanks for the input, @colemonnahan ! That does make sense to me - I guess I was initially concerned about the commit history being full of commits related to document() and potential merge conflicts (I'm a new git user and still getting over my fear of conflicts :) ), but it is better that than having issues with running document() and/or check() down the line and someone who did not write the code that caused the problem having to figure out why. 

I'll be sure to run ```devtools::check()``` and ```devtools::document()``` before submitting pull requests for anything I contribute from now on, as it seems like good practice. Perhaps this suggestion could be added to the r4ss workflow wiki page, if Ian agrees with this philosophy.

**Comment by iantaylor-NOAA** [comment]
I think updating the workflow document on the wiki to suggest folks should run `devtools::document()` and then `devtools::check()` before issuing pull requests is a good idea. @k-doering-NOAA you're welcome to add something now or I can edit the wiki next week.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA sounds good. I can do it next week, since I brought all this up. Thank you!

**Comment by e-perl-NOAA** [comment]
@iantaylor-NOAA can this issue be closed since there is a wiki for the development workflow plus a greater reliance on GitHub actions?
