### ISSUE TITLE
`SS_write()` failed to write when `dir` pointed to recursive directory

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#856]
https://github.com/r4ss/r4ss/blob/2d48e892a7c5a2a79c26a1fa4c3e74ff0e90cc0b/R/SS_write.R#L55
failed when dir input was to a non-existent nested directory. Can I add recursive = TRUE to the above line?

**Comment by iantaylor-NOAA** [comment]
Yes, please do. Thank you @kellijohnson-NOAA.

The `copy_SS_inputs()` function has `recursive = FALSE` by default but the user can override: https://github.com/r4ss/r4ss/blob/main/R/copy_SS_inputs.R#L13-L15. I guess I was afraid of creating a deeply nested set of directories if you had a typo, but in hindsight that's silly because you will figure that out when you look for your model files and fix it. So probably better to take that out and set `recursive = TRUE` by default throughout r4ss (it's already present in a few other places).
