### ISSUE TITLE
[Feature]: Move text in subplots of composition plots

### ISSUE THREAD

**Issue by okenk** [r4ss/r4ss#858]
### Describe the feature request.

For the comp_lenfit and comp_agefit plots, friendly STAR panel member @kristinmarshall-NOAA pointed out that, at least [in our case](https://github.com/pfmc-assessments/canary_2023), the fleet name overlapped with the adjusted and effective sample sizes in many cases. One easy fix for this, I think, would be to move the adjusted and effective sample sizes text to the bottom left instead of the top right

### Describe alternatives you have considered

1. Move the fleet name to the bottom of each panel and keep the sample sizes at the top
2. Build a function that detects whether text overlaps and adjusts text size accordingly
3. Switch to ggplot

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by iantaylor-NOAA** [comment]
This is a good idea that's sadly hard to fix. I just spent a little while staring at the code that controls this, but of course it's very complex.

`SS_plots()` calls `SSplotComps()` which calls `make_multifig()` which makes the legends and has inputs to control the legend location. However, making those controls available to the user via `SS_plots()` will require a bunch of changes and maybe be unnecessary given that the proposed change is probably better for every two sex model. Also, the controls are not "topright", but things like `par()$usr[1]` with adjustments for the position relative to the x and y values. That was the best I could do in 2008.

Single sex models don't have the negative y-axis range, so they wouldn't get a change. That's not a big deal.

The last consideration is that if the data are entered as sex = 1 and 2 rather than sex = 3, there should be different sample sizes for females and males that appear at the top and bottom right of each plot. I'm not actually seeing it work that way for Black Rockfish, but it would be good to maintain the option of that working correctly someday.

A solution that deals with all of these considerations and doesn't break anything seems hard right now.

Would one of the these inferior alternatives be adequate for your report?
* remake these plots using shorter fleet names: `SS_plots(..., fleetnames = short_fleetnames, plot = 13:18)`
* decrease the font from the default 10: `SS_plots(..., ptsize = 8, plot = 13:18)`
* make a branch of r4ss and change the settings in a non-generalized way but doesn't get merged into `main`
* [probably the least good option] remove the sample sizes in the legends `SS_plots(..., showsampsize = FALSE, showeffN = FALSE)`

**Comment by okenk** [comment]
Ahh, I see. I was not aware of all of these `SS_plots` arguments, I think we can make something work! Thanks!

**Comment by iantaylor-NOAA** [comment]
Work arounds with existing options were adequate so closing this issue.
