### ISSUE TITLE
[Feature]: More pronounced fit line for mean length/size/age plots

### ISSUE THREAD

**Issue by MOshima-PIFSC** [r4ss/r4ss#859]
### Describe the feature request.

When there are many years of composition data, the blue fit line in the mean length/size/age plot is hard to see (see example figure below). 
![image](https://github.com/r4ss/r4ss/assets/78562167/073a0c73-3dc1-4f9a-9e3b-a2851908813c)

### Describe alternatives you have considered

I have a few suggestions: 

- including a parameter that allows the user to adjust the line color and thickness (maybe this is already implemented and I'm missing it?)
- increase the thickness of the line
- make the line match the index fit line (in thickness and color)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by iantaylor-NOAA** [comment]
Hi @MOshima-PIFSC, 
Thank you for the suggestion. This has been annoying me for a while but I never got around to fixing it. I've just pushed a change to the main branch increasing the line width to 3 in 2406ee9.

Having done so, I now see it doesn't exactly match the index fits which use `col = "blue"` rather than `col = 4`, which in recent versions of R is not exactly blue. We can clean up those colors another time, but let me know if this fix is good enough for now.

**Comment by MOshima-PIFSC** [comment]
Thanks @iantaylor-NOAA for getting to this so quickly. `lwd=3` works great. It's a big improvement! 
![image](https://github.com/r4ss/r4ss/assets/78562167/ba117b1f-84ed-4718-8563-6db29d9349af)

Thanks again!

**Comment by iantaylor-NOAA** [comment]
happy to help
