### ISSUE TITLE
make data size plots in SSplotData work with seasonal models

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/r4ss#89]
Issue #88 was a bug associated with mismatch of integer years and seasonal catches. All size and precision of data types could be represented seasonally but this might require an extensive rewrite of the function.

**Comment by taylori** [comment]
The `development` branch version of the `SSplotData` function (called by `SS_plots` in group 24) now produces the scaled bubble plot for seasonal models. 

Rather than show separate bubbles for each season, which would have been more complex and probably result in a noisy plot, the plot simply aggregates the observations within each season. The size of the bubbles is based on either the sum of samples within each year (for things like comps) or the average among observations within a year (for things like index uncertainty).

An additional change to `SSplotData` is the use of a new `subplot` input to be consistent with other r4ss functions. The default is `subplot=1:2` which produces both unscaled (`subplot=1`) and scaled (`subplot=2`) versions of the plots. This replaces the combination of `datasize=TRUE/FALSE` and `both=TRUE/FALSE` to control whether to scale the bubbles and produce just one plot or both scaled and unscaled plots.

Also, the scaling of tag recapture data wasn't working correctly, so that has been improved even for annual models.

This issue can be closed once the users of seasonal models confirm that the results look right. I just tested the changes on models for Eastern Baltic Cod and Brown Shrimp, but without being really familiar with the data, it's hard to confirm that the scaling looks correct.

Install the development branch via `devtools::install_github('r4ss/r4ss', ref='development')`

**Comment by iantaylor-NOAA** [comment]
Changes seem to be working fine. Closing this issue.
