### ISSUE TITLE
[Feature]: Surplus production vs. biomass plot

### ISSUE THREAD

**Issue by e-perl-NOAA** [r4ss/r4ss#910]
### Describe the feature request.

Requested by @akatan999 in ss3 discussion [here](https://github.com/nmfs-ost/ss3-source-code/discussions/565#discussioncomment-8408231):
Following recent paper (https://cdnsciencepub.com/doi/pdf/10.1139/cjfas-2022-0168), it would be better to plot Surplus production vs. spawining stock biomass instead of total biomass. Or at least add it.

### Describe alternatives you have considered

Having users create plots themselves.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by iantaylor-NOAA** [comment]
@akatan999, see figure added via https://github.com/r4ss/r4ss/commit/6132b5308c1b8e6c2a963346b168a07b1fd85a20 to a `surplus-production` branch which you can install via `pak::pak("r4ss/r4ss@surplus-production")` (or similar with `remotes::install_github()`). Example below is for Petrale Sole showing that things look quite different vs the total biomass version.

Right now it's hard-wired to say "Spawning output" but I have an unfinished project in the works to make the spawning biomass / spawning output labels better in #838 which can apply to this plot as well.

![image](https://github.com/r4ss/r4ss/assets/4992918/ed6f6416-7353-4287-8d3a-542a85329530)

**Comment by akatan999** [comment]
Thanks Ian, that was exactly my point, the two looks very different but the second is more useful from a pragmatic point of view as explained by the paper from Forrest.

**Comment by iantaylor-NOAA** [comment]
Shelton Harley pointed out that the old code was wrong for seasonal models because it was summing biomass across seasons instead of taking the mean. My in-process change in the [surplus-production](https://github.com/r4ss/r4ss/compare/main...surplus-production#diff-8aba435c74cf3fe5556008d1a9ff432298fd66ad18261969ae9090bf79cee866R204-R208) branch is incorrect in the other direction because it takes the mean across seasons but also across areas which should be summed. I will try to get back to this issue before too long to make that logic correct and finish adding the alternative format with SSB instead of total biomass.

**Comment by iantaylor-NOAA** [comment]
The error in the newer surplus production vs biomass plot associated with spatial models identified by Shelton Harley was resolved in Pull Request #977 thanks to @e-perl-NOAA.
