### ISSUE TITLE
[Feature]:  add release (and tag) to r4ss?

### ISSUE THREAD

**Issue by k-doering-NOAA** [r4ss/r4ss#951]
### Describe the feature request.

#945 caused some breaking changes in SSMSE.

I'm wondering if it would be possible to release (and therefore make a tag) r4ss version 1.50.0 so it is easier to communicate which version of r4ss should be used with SSMSE going forward?

### Describe alternatives you have considered

Just use the version listed in the description file already in r4ss

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by iantaylor-NOAA** [comment]
Thanks @k-doering-NOAA. I meant to post messages to the dependent packages that use the old naming convention before the merge but forgot.
Would it be helpful to release both r4ss 1.49.3 (immediately prior to change) as well as 1.50.0 so that SSMSE could work again without change by using the 1.49.3 release?

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA, that sounds like it could be helpful for the short term, if it is still possible to release 1.49.3 as well! Thank you !

**Comment by iantaylor-NOAA** [comment]
Thanks for the welcome nudge to do these releases @k-doering-NOAA.
FYI, I'm not great adding tags via git but GitHub allowed me to pick from recent commits for the 1.49.3 release and apply a new tag retroactively.
If the releases don't meet the needs of SSMSE, please feel free to reopen this issue.

**Comment by k-doering-NOAA** [comment]
Thank you, this is really helpful!

**Comment by efletcherPIFSC** [comment]
@iantaylor-NOAA It would be helpful if there are new GIthub Releases for the new r4ss updates:  The "Latest Release" is **r4ss version 1.51.0**  (Dec 2024)

<img width="314" height="174" alt="Image" src="https://github.com/user-attachments/assets/a515006a-2d15-48f3-b18a-2f390c874b0b" />

---

 r4ss release notes since 1.51.0 on NEWS.md

- r4ss 1.54.0 (April 2026) https://github.com/r4ss/r4ss/blob/main/NEWS.md#r4ss-1540-april-2026
- r4ss 1.52.0 (April 2025) https://github.com/r4ss/r4ss/blob/main/NEWS.md#r4ss-1520-april-2025

**Comment by iantaylor-NOAA** [comment]
@efletcherPIFSC, thanks for the reminder. Given the pretty continuous evolution of the package, it's hard for me to remember to pause to add tags, but since I can remember to occasionally update NEWS.md (still not often enough), I will try to also remember to create a release in parallel with those changes.

For those who are using renv or other version tracking tools, I can see the benefit of having a version number.
